
// File generated by noodle version N-2018.03#7d02e3ca79#180723, Fri Jan 11 16:58:52 2019
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// noodle -Pc -B -Iisg +wisg -D__tct_patch__=300 +NOrlt -D__chess__ -D__programmers_view__ tinycore2

// File: compile_time_constants.c
// Test compile-time constants : size and alignment in default and other suitable memories

extern "C" {


} //extern "C"  (0 functions)
