
// File generated by noodle version N-2018.03#7d02e3ca79#180723, Fri Jan 11 16:58:52 2019
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// noodle -Pc -B -Iisg +wisg -D__tct_patch__=300 +NOrlt -D__chess__ -D__programmers_view__ tinycore2

// File: constant_generation.c
// Test constant generation

extern "C" {



// Relocatable addresses, range determined by memory
// (Type of object is irrelevant, but must be allocatable, so using the primitive type)

extern tinycore2_primitive::pmtype chess_storage(PM) o_PM;
//!? no suitable return argument register(s)
//!void chess_storage(PM) * ctptr_PM() { return &o_PM; }

extern tinycore2_primitive::word chess_storage(DM) o_DM;
//!? no suitable return argument register(s)
//!void chess_storage(DM) * ctptr_DM() { return &o_DM; }


} //extern "C"  (2 functions)
