
// File generated by noodle version N-2018.03#7d02e3ca79#180723, Fri Jan 11 16:58:52 2019
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// noodle -Pc -B -Iisg +wisg -D__tct_patch__=300 +NOrlt -D__chess__ -D__programmers_view__ tinycore2

// File: register_moves.c
// Test register moves
// (Output is written as an in-out reference, so that it cannot be overlayed with the input)

//! Connection analysis may reveal that certain moves are not available, and those tests are skipped.
//! Note that the connection may be direct or indirect.
//! However, indirect connections via spill memory are not considered at this time!

extern "C" {


} //extern "C"  (0 functions)
