
// File generated by noodle version N-2018.03#7d02e3ca79#180723, Thu Jan 24 11:28:36 2019
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// noodle -B -I.. -I../isg -I../runtime/include -I../../io_modules -I/CMC/tools/synopsys/asip_designer_vN-2018.03-SP3/linux64/chessdir/../examples/io_modules -D__tct_patch__=300 -itlx_chess.h +wlib/Release/chesswork ../runtime/src/stdio.c tlx

.dir 0 "/users/benacer/Desktop/sha256_orig/sha256/lib/runtime/src"
.text local 1 void__ihosted_clib_io
.src_ref 0 "stdio.c" 83
 nop
.src_ref 0 "stdio.c" 84
 nop
.src_ref 0 "stdio.c" 85
 nop
.src_ref 0 "stdio.c" 86
.label _hosted_clib_io_brkpt
.src_ref 0 "stdio.c" 87
 nop
