
// File generated by noodle version N-2018.03#7d02e3ca79#180723, Fri Jan 25 16:14:37 2019
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// noodle -Pc -Iisg +wisg -D__tct_patch__=300 -D__chess__ -D__programmers_view__ tinycore2

#ifdef __chess__
#error "generated native file not intended for compilation by chess"
#endif

// Processor specific IO functions
// used in Checkers ISS C Variable Info (using Dwarf)
//  and in Checkers ISS hosted IO via stdio.h functions

#include <string>
#include "Mdl_[=getdesign_name=]_uicore.h"

int [=getdesign_name=]_read0(Checkers_uicore* uicore, long long* val, int /*n=1*/, int si, AddressType addr);
int [=getdesign_name=]_write0(Checkers_uicore* uicore, const long long* val, int /*n=1*/, int si, AddressType addr);
int [=getdesign_name=]_read1_record0(Checkers_uicore* uicore, long long* val, int /*n=1*/, int si, AddressType addr);
int [=getdesign_name=]_write1_record0(Checkers_uicore* uicore, const long long* val, int /*n=1*/, int si, AddressType addr);
