
// File generated by pdg version N-2018.03#7d02e3ca79#180723, Sun Apr 14 19:29:24 2019
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// pdg -P -B -Iisg +wisg -I../../io_modules -I/CMC/tools/synopsys/asip_designer_vN-2018.03-SP3/linux64/chessdir/../examples/io_modules -D__tct_patch__=300 -D__checkers__ tlx

#include <cstdio>
#include <iostream>
#include <iomanip>
#include <map>
#include <set>
#include <string>
#include <sstream>
#include <fstream>
#include <cassert>

#include "tlx_iss_types.h"

#ifdef PDG_INLINE_PRIMITIVES
#include "tlx_inline_primitives.h"
#endif
using namespace tlx_primitive;

std::string current_line;

#if (defined(_MSC_VER) && _MSC_VER < 1300)

std::ostream& operator<<(std::ostream& os, tct_long_long n)
{
    char buf[128];
    if (os.flags() & std::ios_base::hex) {
        sprintf(buf, "%I64x", n);
    }
    else if (os.flags() & std::ios_base::oct) {
        sprintf(buf, "%I64o", n);
    }
    else {
        sprintf(buf, "%I64d", n);
    }
    os << buf;
    return os;
}

std::ostream& operator<<(std::ostream& os, tct_ulong_long n)
{
    char buf[128];
    if (os.flags() & std::ios_base::hex) {
        sprintf(buf, "%I64x", n);
    }
    else if (os.flags() & std::ios_base::oct) {
        sprintf(buf, "%I64o", n);
    }
    else {
        sprintf(buf, "%I64d", n);
    }
    os << buf;
    return os;
}
std::istream& operator>>(std::istream& is, tct_long_long& n)
{
    n = 0;

    int ndg = 0;

    char c;
    is >> c;
    if (!is)
        return is;
    int neg = 0;
    if (c == '-') {
        neg = 1;
        is.get(c);
        if (!is)
            return is;
    }
    if (is.flags() & std::ios_base::hex) {
        int done = 0;
        while(is && !done) {
            switch(c) {
                case '0': n = n*16     ; ndg++; break;
                case '1': n = n*16 +  1; ndg++; break;
                case '2': n = n*16 +  2; ndg++; break;
                case '3': n = n*16 +  3; ndg++; break;
                case '4': n = n*16 +  4; ndg++; break;
                case '5': n = n*16 +  5; ndg++; break;
                case '6': n = n*16 +  6; ndg++; break;
                case '7': n = n*16 +  7; ndg++; break;
                case '8': n = n*16 +  8; ndg++; break;
                case '9': n = n*16 +  9; ndg++; break;
                case 'a':
                case 'A': n = n*16 + 10; ndg++; break;
                case 'b':
                case 'B': n = n*16 + 11; ndg++; break;
                case 'c':
                case 'C': n = n*16 + 12; ndg++; break;
                case 'd':
                case 'D': n = n*16 + 13; ndg++; break;
                case 'e':
                case 'E': n = n*16 + 14; ndg++; break;
                case 'f':
                case 'F': n = n*16 + 15; ndg++; break;
                case 'x':
                case 'X':
                    if (ndg == 1 && n == 0)
                        ndg = 0;
                    else
                        done = 1;
                    break;
                default:
                    done = 1;
            }
            if (done)
                is.putback(c);
            else
                is.get(c);
        }
        if (ndg > 0)
            is.clear(std::ios_base::goodbit);
        else
            is.clear(std::ios_base::badbit|is.rdstate());
        if (neg)
            n = -n;
    }
    else if (is.flags() & std::ios_base::oct) {
        int done = 0;
        while(is && !done) {
            switch(c) {
                case '0': n = n*8    ; ndg++; break;
                case '1': n = n*8 + 1; ndg++; break;
                case '2': n = n*8 + 2; ndg++; break;
                case '3': n = n*8 + 3; ndg++; break;
                case '4': n = n*8 + 4; ndg++; break;
                case '5': n = n*8 + 5; ndg++; break;
                case '6': n = n*8 + 6; ndg++; break;
                case '7': n = n*8 + 7; ndg++; break;
                default:
                    done = 1;
            }
            if (done)
                is.putback(c);
            else
                is.get(c);
        }
        if (ndg > 0)
            is.clear(std::ios_base::goodbit);
        else
            is.clear(std::ios_base::badbit|is.rdstate());
        if (neg)
            n = -n;
    }
    else { // dec
        int done = 0;
        while(is && !done) {
            switch(c) {
                case '0': n = n*10    ; ndg++; break;
                case '1': n = n*10 + 1; ndg++; break;
                case '2': n = n*10 + 2; ndg++; break;
                case '3': n = n*10 + 3; ndg++; break;
                case '4': n = n*10 + 4; ndg++; break;
                case '5': n = n*10 + 5; ndg++; break;
                case '6': n = n*10 + 6; ndg++; break;
                case '7': n = n*10 + 7; ndg++; break;
                case '8': n = n*10 + 8; ndg++; break;
                case '9': n = n*10 + 9; ndg++; break;
                default :
                    done = 1;
            }
            if (done)
                is.putback(c);
            else
                is.get(c);
        }
        if (ndg > 0)
            is.clear(std::ios_base::goodbit);
        else
            is.clear(std::ios_base::badbit|is.rdstate());
        if (neg)
            n = -n;
    }
    return is;
}

std::istream& operator>>(std::istream& is, tct_ulong_long& n)
{
    tct_long_long t;
    is >> t;
    if (is)
        n = t;
    return is;
}
#endif

typedef bool boolean;

int pdg_error_count = 0;
std::ostream* error_stream;

template <typename T>
void failure(const T& t1, const T& t2) {
    ++pdg_error_count;
    *error_stream << current_line << " ; expected " << t1 << ", found " << t2 << std::endl;
    std::cerr << current_line << " ; expected " << t1 << ", found " << t2 << std::endl;
}

template <typename T>
void read_from_stream(std::istream& is, T& result) {
    unsigned u;
    is >> u;
    result = u;
}
template <typename T>
void read_from_stream_ll(std::istream& is, T& result) {
    tct_ulong_long ull;
    is >> ull;
    result = ull;
}
static bool between(char l, char x, char h) {
    return l <= x && x <= h;
}

static unsigned digit2hex(char c) {
    if (between('0', c, '9')) {
        return c - '0';
    } else if (between('a', c, 'f')) {
        return c - 'a' + 10;
    } else if (between('A', c, 'F')) {
        return c - 'A' + 10;
    }
    return 0;
}

void read_from_stream_lla(std::istream& is, tct_ulong_long* result, const unsigned n) {
    const int octo_count = CHESS_LLAS(n);
    const int hex_digits = (n + 3) / 4;
    for (int i = 0; i < octo_count; ++i) {
        tct_ulong_long ull = 0;
        for (int j = 0; j < ((i == 0 && hex_digits % 16) ? hex_digits % 16 : 16); ++j) {
            ull <<= 4;
            char c;
            is >> c;
            ull += digit2hex(c);
        }
        result[octo_count - i - 1] = ull;
    }
}

void read_from_stream_lla(std::istream& is, tct_long_long* result, const unsigned n) {
    const int octo_count = CHESS_LLAS(n);
    const int hex_digits = (n + 3) / 4;
    for (int i = 0; i < octo_count; ++i) {
        tct_ulong_long ull = 0;
        for (int j = 0; j < ((i == 0 && hex_digits % 16) ? hex_digits % 16 : 16); ++j) {
            ull <<= 4;
            char c;
            is >> c;
            ull += digit2hex(c);
        }
        result[octo_count - i - 1] = ull;
    }
    if (n % 64) result[octo_count - 1] = CHESS_EXTENDLL(result[octo_count - 1], n % 64);
}

tct_ulong_long buf_ull[1024];
tct_ulong_long buf_ull2[1024];
tct_long_long buf_ll[1024];
tct_long_long buf_ll2[1024];

bool operator!=(tlx_primitive::addr x1, tlx_primitive::addr x2) {
    return toVBit(x1) != toVBit(x2);
}

bool operator!=(tlx_primitive::int16 x1, tlx_primitive::int16 x2) {
    return toVBit(x1) != toVBit(x2);
}

bool operator!=(tlx_primitive::int16p x1, tlx_primitive::int16p x2) {
    return toVBit(x1) != toVBit(x2);
}

bool operator!=(tlx_primitive::int26 x1, tlx_primitive::int26 x2) {
    return toVBit(x1) != toVBit(x2);
}

bool operator!=(tlx_primitive::int5 x1, tlx_primitive::int5 x2) {
    return toVBit(x1) != toVBit(x2);
}

bool operator!=(tlx_primitive::iword x1, tlx_primitive::iword x2) {
    return toVBit(x1) != toVBit(x2);
}

bool operator!=(tlx_primitive::uint1 x1, tlx_primitive::uint1 x2) {
    return toVBit(x1) != toVBit(x2);
}

bool operator!=(tlx_primitive::uint16 x1, tlx_primitive::uint16 x2) {
    return toVBit(x1) != toVBit(x2);
}

bool operator!=(tlx_primitive::uint4 x1, tlx_primitive::uint4 x2) {
    return toVBit(x1) != toVBit(x2);
}

bool operator!=(tlx_primitive::w08 x1, tlx_primitive::w08 x2) {
    return toVBit(x1) != toVBit(x2);
}

bool operator!=(tlx_primitive::w16 x1, tlx_primitive::w16 x2) {
    return toVBit(x1) != toVBit(x2);
}

bool operator!=(tlx_primitive::w32 x1, tlx_primitive::w32 x2) {
    return toVBit(x1) != toVBit(x2);
}

void test_w32_add_w32_w32_uint1(std::istream& is) {
    tlx_primitive::w32 result_expected;
    tlx_primitive::w32 t0;
    tlx_primitive::w32 t1;
    tlx_primitive::uint1 t2;
    tlx_primitive::uint1 t2_expected;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    read_from_stream(is, t2_expected);
    tlx_primitive::w32 result = add(t0, t1, t2);
    if (result != result_expected) { failure(result_expected, result); return; }
    if (t2 != t2_expected) { failure(t2_expected, t2); return; }
}

void test_w32_add_w32_w32(std::istream& is) {
    tlx_primitive::w32 result_expected;
    tlx_primitive::w32 t0;
    tlx_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    tlx_primitive::w32 result = add(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_sub_w32_w32_uint1(std::istream& is) {
    tlx_primitive::w32 result_expected;
    tlx_primitive::w32 t0;
    tlx_primitive::w32 t1;
    tlx_primitive::uint1 t2;
    tlx_primitive::uint1 t2_expected;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    read_from_stream(is, t2_expected);
    tlx_primitive::w32 result = sub(t0, t1, t2);
    if (result != result_expected) { failure(result_expected, result); return; }
    if (t2 != t2_expected) { failure(t2_expected, t2); return; }
}

void test_w32_addx_w32_w32_uint1_uint1(std::istream& is) {
    tlx_primitive::w32 result_expected;
    tlx_primitive::w32 t0;
    tlx_primitive::w32 t1;
    tlx_primitive::uint1 t2;
    tlx_primitive::uint1 t3;
    tlx_primitive::uint1 t3_expected;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, t2);
    read_from_stream(is, result_expected);
    read_from_stream(is, t3_expected);
    tlx_primitive::w32 result = addx(t0, t1, t2, t3);
    if (result != result_expected) { failure(result_expected, result); return; }
    if (t3 != t3_expected) { failure(t3_expected, t3); return; }
}

void test_w32_subx_w32_w32_uint1_uint1(std::istream& is) {
    tlx_primitive::w32 result_expected;
    tlx_primitive::w32 t0;
    tlx_primitive::w32 t1;
    tlx_primitive::uint1 t2;
    tlx_primitive::uint1 t3;
    tlx_primitive::uint1 t3_expected;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, t2);
    read_from_stream(is, result_expected);
    read_from_stream(is, t3_expected);
    tlx_primitive::w32 result = subx(t0, t1, t2, t3);
    if (result != result_expected) { failure(result_expected, result); return; }
    if (t3 != t3_expected) { failure(t3_expected, t3); return; }
}

void test_w32_band_w32_w32(std::istream& is) {
    tlx_primitive::w32 result_expected;
    tlx_primitive::w32 t0;
    tlx_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    tlx_primitive::w32 result = band(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_bor_w32_w32(std::istream& is) {
    tlx_primitive::w32 result_expected;
    tlx_primitive::w32 t0;
    tlx_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    tlx_primitive::w32 result = bor(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_bxor_w32_w32(std::istream& is) {
    tlx_primitive::w32 result_expected;
    tlx_primitive::w32 t0;
    tlx_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    tlx_primitive::w32 result = bxor(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_sge_w32_w32(std::istream& is) {
    tlx_primitive::w32 result_expected;
    tlx_primitive::w32 t0;
    tlx_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    tlx_primitive::w32 result = sge(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_sgt_w32_w32(std::istream& is) {
    tlx_primitive::w32 result_expected;
    tlx_primitive::w32 t0;
    tlx_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    tlx_primitive::w32 result = sgt(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_sle_w32_w32(std::istream& is) {
    tlx_primitive::w32 result_expected;
    tlx_primitive::w32 t0;
    tlx_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    tlx_primitive::w32 result = sle(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_slt_w32_w32(std::istream& is) {
    tlx_primitive::w32 result_expected;
    tlx_primitive::w32 t0;
    tlx_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    tlx_primitive::w32 result = slt(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_seq_w32_w32(std::istream& is) {
    tlx_primitive::w32 result_expected;
    tlx_primitive::w32 t0;
    tlx_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    tlx_primitive::w32 result = seq(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_sne_w32_w32(std::istream& is) {
    tlx_primitive::w32 result_expected;
    tlx_primitive::w32 t0;
    tlx_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    tlx_primitive::w32 result = sne(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_sgeu_w32_w32(std::istream& is) {
    tlx_primitive::w32 result_expected;
    tlx_primitive::w32 t0;
    tlx_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    tlx_primitive::w32 result = sgeu(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_sgtu_w32_w32(std::istream& is) {
    tlx_primitive::w32 result_expected;
    tlx_primitive::w32 t0;
    tlx_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    tlx_primitive::w32 result = sgtu(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_sleu_w32_w32(std::istream& is) {
    tlx_primitive::w32 result_expected;
    tlx_primitive::w32 t0;
    tlx_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    tlx_primitive::w32 result = sleu(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_sltu_w32_w32(std::istream& is) {
    tlx_primitive::w32 result_expected;
    tlx_primitive::w32 t0;
    tlx_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    tlx_primitive::w32 result = sltu(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_sra_w32_w32(std::istream& is) {
    tlx_primitive::w32 result_expected;
    tlx_primitive::w32 t0;
    tlx_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    tlx_primitive::w32 result = sra(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_sll_w32_w32(std::istream& is) {
    tlx_primitive::w32 result_expected;
    tlx_primitive::w32 t0;
    tlx_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    tlx_primitive::w32 result = sll(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_srl_w32_w32(std::istream& is) {
    tlx_primitive::w32 result_expected;
    tlx_primitive::w32 t0;
    tlx_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    tlx_primitive::w32 result = srl(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_xtd_w32_w32(std::istream& is) {
    tlx_primitive::w32 result_expected;
    tlx_primitive::w32 t0;
    tlx_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    tlx_primitive::w32 result = xtd(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_mul_w32_w32(std::istream& is) {
    tlx_primitive::w32 result_expected;
    tlx_primitive::w32 t0;
    tlx_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    tlx_primitive::w32 result = mul(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_void_lmulss_w32_w32_w32_w32(std::istream& is) {
    tlx_primitive::w32 t0;
    tlx_primitive::w32 t1;
    tlx_primitive::w32 t2;
    tlx_primitive::w32 t2_expected;
    tlx_primitive::w32 t3;
    tlx_primitive::w32 t3_expected;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, t2_expected);
    read_from_stream(is, t3_expected);
    lmulss(t0, t1, t2, t3);
    if (t2 != t2_expected) { failure(t2_expected, t2); return; }
    if (t3 != t3_expected) { failure(t3_expected, t3); return; }
}

void test_void_lmulsu_w32_w32_w32_w32(std::istream& is) {
    tlx_primitive::w32 t0;
    tlx_primitive::w32 t1;
    tlx_primitive::w32 t2;
    tlx_primitive::w32 t2_expected;
    tlx_primitive::w32 t3;
    tlx_primitive::w32 t3_expected;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, t2_expected);
    read_from_stream(is, t3_expected);
    lmulsu(t0, t1, t2, t3);
    if (t2 != t2_expected) { failure(t2_expected, t2); return; }
    if (t3 != t3_expected) { failure(t3_expected, t3); return; }
}

void test_void_lmuluu_w32_w32_w32_w32(std::istream& is) {
    tlx_primitive::w32 t0;
    tlx_primitive::w32 t1;
    tlx_primitive::w32 t2;
    tlx_primitive::w32 t2_expected;
    tlx_primitive::w32 t3;
    tlx_primitive::w32 t3_expected;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, t2_expected);
    read_from_stream(is, t3_expected);
    lmuluu(t0, t1, t2, t3);
    if (t2 != t2_expected) { failure(t2_expected, t2); return; }
    if (t3 != t3_expected) { failure(t3_expected, t3); return; }
}

void test_w32_clb_w32(std::istream& is) {
    tlx_primitive::w32 result_expected;
    tlx_primitive::w32 t0;
    read_from_stream(is, t0);
    read_from_stream(is, result_expected);
    tlx_primitive::w32 result = clb(t0);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_extend_sign_w08(std::istream& is) {
    tlx_primitive::w32 result_expected;
    tlx_primitive::w08 t0;
    read_from_stream(is, t0);
    read_from_stream(is, result_expected);
    tlx_primitive::w32 result = extend_sign(t0);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_extend_zero_w08(std::istream& is) {
    tlx_primitive::w32 result_expected;
    tlx_primitive::w08 t0;
    read_from_stream(is, t0);
    read_from_stream(is, result_expected);
    tlx_primitive::w32 result = extend_zero(t0);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_extend_sign_w16(std::istream& is) {
    tlx_primitive::w32 result_expected;
    tlx_primitive::w16 t0;
    read_from_stream(is, t0);
    read_from_stream(is, result_expected);
    tlx_primitive::w32 result = extend_sign(t0);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_extend_zero_w16(std::istream& is) {
    tlx_primitive::w32 result_expected;
    tlx_primitive::w16 t0;
    read_from_stream(is, t0);
    read_from_stream(is, result_expected);
    tlx_primitive::w32 result = extend_zero(t0);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w08_extract_w08_w32(std::istream& is) {
    tlx_primitive::w08 result_expected;
    tlx_primitive::w32 t0;
    read_from_stream(is, t0);
    read_from_stream(is, result_expected);
    tlx_primitive::w08 result = extract_w08(t0);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w16_extract_w16_w32(std::istream& is) {
    tlx_primitive::w16 result_expected;
    tlx_primitive::w32 t0;
    read_from_stream(is, t0);
    read_from_stream(is, result_expected);
    tlx_primitive::w16 result = extract_w16(t0);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_bool_eqz_w32(std::istream& is) {
    bool result_expected;
    tlx_primitive::w32 t0;
    read_from_stream(is, t0);
    read_from_stream(is, result_expected);
    bool result = eqz(t0);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_bool_nez_w32(std::istream& is) {
    bool result_expected;
    tlx_primitive::w32 t0;
    read_from_stream(is, t0);
    read_from_stream(is, result_expected);
    bool result = nez(t0);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_void_nop(std::istream& is) {
    nop();
}

void test_w32_pcadd_w32_w32(std::istream& is) {
    tlx_primitive::w32 result_expected;
    tlx_primitive::w32 t0;
    tlx_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    tlx_primitive::w32 result = pcadd(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_DUCbCr_w32_w32_w32_w32_w32_w32_w32(std::istream& is) {
    tlx_primitive::w32 result_expected;
    tlx_primitive::w32 t0;
    tlx_primitive::w32 t1;
    tlx_primitive::w32 t2;
    tlx_primitive::w32 t3;
    tlx_primitive::w32 t4;
    tlx_primitive::w32 t5;
    tlx_primitive::w32 t5_expected;
    tlx_primitive::w32 t6;
    tlx_primitive::w32 t6_expected;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, t2);
    read_from_stream(is, t3);
    read_from_stream(is, t4);
    read_from_stream(is, result_expected);
    read_from_stream(is, t5_expected);
    read_from_stream(is, t6_expected);
    tlx_primitive::w32 result = DUCbCr(t0, t1, t2, t3, t4, t5, t6);
    if (result != result_expected) { failure(result_expected, result); return; }
    if (t5 != t5_expected) { failure(t5_expected, t5); return; }
    if (t6 != t6_expected) { failure(t6_expected, t6); return; }
}

void test_void_jpeg_fdct_w32_w32_w32_w32_w32_w32_w32_w32_w32_w32_w32_w32_w32_w32_w32_w32(std::istream& is) {
    tlx_primitive::w32 t0;
    tlx_primitive::w32 t1;
    tlx_primitive::w32 t2;
    tlx_primitive::w32 t3;
    tlx_primitive::w32 t4;
    tlx_primitive::w32 t5;
    tlx_primitive::w32 t6;
    tlx_primitive::w32 t7;
    tlx_primitive::w32 t8;
    tlx_primitive::w32 t8_expected;
    tlx_primitive::w32 t9;
    tlx_primitive::w32 t9_expected;
    tlx_primitive::w32 t10;
    tlx_primitive::w32 t10_expected;
    tlx_primitive::w32 t11;
    tlx_primitive::w32 t11_expected;
    tlx_primitive::w32 t12;
    tlx_primitive::w32 t12_expected;
    tlx_primitive::w32 t13;
    tlx_primitive::w32 t13_expected;
    tlx_primitive::w32 t14;
    tlx_primitive::w32 t14_expected;
    tlx_primitive::w32 t15;
    tlx_primitive::w32 t15_expected;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, t2);
    read_from_stream(is, t3);
    read_from_stream(is, t4);
    read_from_stream(is, t5);
    read_from_stream(is, t6);
    read_from_stream(is, t7);
    read_from_stream(is, t8_expected);
    read_from_stream(is, t9_expected);
    read_from_stream(is, t10_expected);
    read_from_stream(is, t11_expected);
    read_from_stream(is, t12_expected);
    read_from_stream(is, t13_expected);
    read_from_stream(is, t14_expected);
    read_from_stream(is, t15_expected);
    jpeg_fdct(t0, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15);
    if (t8 != t8_expected) { failure(t8_expected, t8); return; }
    if (t9 != t9_expected) { failure(t9_expected, t9); return; }
    if (t10 != t10_expected) { failure(t10_expected, t10); return; }
    if (t11 != t11_expected) { failure(t11_expected, t11); return; }
    if (t12 != t12_expected) { failure(t12_expected, t12); return; }
    if (t13 != t13_expected) { failure(t13_expected, t13); return; }
    if (t14 != t14_expected) { failure(t14_expected, t14); return; }
    if (t15 != t15_expected) { failure(t15_expected, t15); return; }
}
typedef std::map<std::string, void(*)(std::istream&)> TestDrivers;
void register_drivers0(TestDrivers& test_drivers) {
    test_drivers["w32_add_w32_w32_uint1"] = test_w32_add_w32_w32_uint1;
    test_drivers["w32_add_w32_w32"] = test_w32_add_w32_w32;
    test_drivers["w32_sub_w32_w32_uint1"] = test_w32_sub_w32_w32_uint1;
    test_drivers["w32_addx_w32_w32_uint1_uint1"] = test_w32_addx_w32_w32_uint1_uint1;
    test_drivers["w32_subx_w32_w32_uint1_uint1"] = test_w32_subx_w32_w32_uint1_uint1;
    test_drivers["w32_band_w32_w32"] = test_w32_band_w32_w32;
    test_drivers["w32_bor_w32_w32"] = test_w32_bor_w32_w32;
    test_drivers["w32_bxor_w32_w32"] = test_w32_bxor_w32_w32;
    test_drivers["w32_sge_w32_w32"] = test_w32_sge_w32_w32;
    test_drivers["w32_sgt_w32_w32"] = test_w32_sgt_w32_w32;
    test_drivers["w32_sle_w32_w32"] = test_w32_sle_w32_w32;
    test_drivers["w32_slt_w32_w32"] = test_w32_slt_w32_w32;
    test_drivers["w32_seq_w32_w32"] = test_w32_seq_w32_w32;
    test_drivers["w32_sne_w32_w32"] = test_w32_sne_w32_w32;
    test_drivers["w32_sgeu_w32_w32"] = test_w32_sgeu_w32_w32;
    test_drivers["w32_sgtu_w32_w32"] = test_w32_sgtu_w32_w32;
    test_drivers["w32_sleu_w32_w32"] = test_w32_sleu_w32_w32;
    test_drivers["w32_sltu_w32_w32"] = test_w32_sltu_w32_w32;
    test_drivers["w32_sra_w32_w32"] = test_w32_sra_w32_w32;
    test_drivers["w32_sll_w32_w32"] = test_w32_sll_w32_w32;
    test_drivers["w32_srl_w32_w32"] = test_w32_srl_w32_w32;
    test_drivers["w32_xtd_w32_w32"] = test_w32_xtd_w32_w32;
    test_drivers["w32_mul_w32_w32"] = test_w32_mul_w32_w32;
    test_drivers["void_lmulss_w32_w32_w32_w32"] = test_void_lmulss_w32_w32_w32_w32;
    test_drivers["void_lmulsu_w32_w32_w32_w32"] = test_void_lmulsu_w32_w32_w32_w32;
    test_drivers["void_lmuluu_w32_w32_w32_w32"] = test_void_lmuluu_w32_w32_w32_w32;
    test_drivers["w32_clb_w32"] = test_w32_clb_w32;
    test_drivers["w32_extend_sign_w08"] = test_w32_extend_sign_w08;
    test_drivers["w32_extend_zero_w08"] = test_w32_extend_zero_w08;
    test_drivers["w32_extend_sign_w16"] = test_w32_extend_sign_w16;
    test_drivers["w32_extend_zero_w16"] = test_w32_extend_zero_w16;
    test_drivers["w08_extract_w08_w32"] = test_w08_extract_w08_w32;
    test_drivers["w16_extract_w16_w32"] = test_w16_extract_w16_w32;
    test_drivers["bool_eqz_w32"] = test_bool_eqz_w32;
    test_drivers["bool_nez_w32"] = test_bool_nez_w32;
    test_drivers["void_nop"] = test_void_nop;
    test_drivers["w32_pcadd_w32_w32"] = test_w32_pcadd_w32_w32;
    test_drivers["w32_DUCbCr_w32_w32_w32_w32_w32_w32_w32"] = test_w32_DUCbCr_w32_w32_w32_w32_w32_w32_w32;
    test_drivers["void_jpeg_fdct_w32_w32_w32_w32_w32_w32_w32_w32_w32_w32_w32_w32_w32_w32_w32_w32"] = test_void_jpeg_fdct_w32_w32_w32_w32_w32_w32_w32_w32_w32_w32_w32_w32_w32_w32_w32_w32;
}
int main() {
    std::set<std::string> unknown_primitives;
    TestDrivers test_drivers;
    register_drivers0(test_drivers);
    error_stream = new std::ofstream("tlx_c_failures.txt");
    std::ifstream in_stream("tlx_testcases.txt");
    assert(in_stream.good());
    std::string s;
    char buf[8192];
    while (!in_stream.eof()) {
        in_stream.getline(buf, 8192);
        if (!in_stream.gcount()) continue;
        current_line = buf;
        std::istringstream is(current_line);
        is.setf(std::ios::hex, std::ios::basefield);
        is >> s;
        if (test_drivers.find(s) != test_drivers.end()) {
            (test_drivers[s])(is);
        }
        else {
            if (unknown_primitives.insert(s).second) {
                std::cerr << "WARNING: skipping test cases for " << s << " (no C implementation)" << std::endl;
            }
        }
    }
    delete error_stream;
    return pdg_error_count;
}
