
// File generated by noodle version N-2018.03#7d02e3ca79#180723, Fri Jan 11 17:23:02 2019
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// noodle -ps -B -Iisg +wisg -D__tct_patch__=300 +NOrlt -D__checkers__ tinycore2

#ifdef __chess__
#error "generated native file not intended for compilation by chess"
#endif

// Primitive types and functions
// used in Checkers ISS and PDG (and possibly native)


#include "tinycore2_iss_types.h"

