
// File generated by noodle version N-2018.03#7d02e3ca79#180723, Fri Jan 11 17:23:01 2019
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// noodle -Pc -B -Iisg +wisg -D__tct_patch__=300 +NOrlt -D__chess__ -D__programmers_view__ tinycore2

#ifdef __chess__
#error "generated native file not intended for compilation by chess"
#endif

// Native C++ types and functions


#include "tinycore2_chess_types.h"

