
// File generated by noodle version N-2018.03#7d02e3ca79#180723, Thu Jan 24 11:26:26 2019
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// noodle -Pc -B -Iisg +wisg -I../../io_modules -I/CMC/tools/synopsys/asip_designer_vN-2018.03-SP3/linux64/chessdir/../examples/io_modules -D__tct_patch__=300 -D__chess__ -D__programmers_view__ tlx

// File: memory_PM.c
// Test memory PM pointer arithmetic stand-alone and with load/store

//!! no load/store instructions found

#ifndef N // arbitrary value, adapt at will
#define N 7
#endif

extern "C" {

//!! signed char

//!! unsigned char

//!! short

//!! unsigned short

//!! int

//!! unsigned

//!! long long

//!! unsigned long long

//!! float

//!! double

//!! void *


} //extern "C"  (0 functions)
