
// File generated by noodle version N-2018.03#7d02e3ca79#180723, Thu Feb 28 14:33:23 2019
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// noodle -Pc -B -Iisg +wisg -I../../io_modules -I/CMC/tools/synopsys/asip_designer_vN-2018.03-SP3/linux64/chessdir/../examples/io_modules -D__tct_patch__=300 -D__chess__ -D__programmers_view__ tlx

// File: standalone_intrinsics.c
// Test standalone intrinsics  (in global namespace)
// (Outputs that cannot be returned as function parameters are discarded)

extern "C" {

int intrc_bool_land_bool_bool(int a0, int a1)
    { return land(a0, a1); }

int intrc_bool_lor_bool_bool(int a0, int a1)
    { return lor(a0, a1); }

int intrc_bool_lxor_bool_bool(int a0, int a1)
    { return lxor(a0, a1); }

int intrc_bool_nez___sint(int a0)
    { return nez(a0); }

int intrc_bool_eqz___sint(int a0)
    { return eqz(a0); }

int intrc_bool_nez___uint(unsigned a0)
    { return nez(a0); }

int intrc_bool_eqz___uint(unsigned a0)
    { return eqz(a0); }

int intrc_bool_nez___Pvoid(void * a0)
    { return nez(a0); }

int intrc_bool_eqz___Pvoid(void * a0)
    { return eqz(a0); }

int intrc___sint_div_remainder___sint___sint___sint(int a0, int a1, int & a2)
    { return div_remainder(a0, a1, a2); }

unsigned long intrc___ulong_div_remainder___uint___uint___uint(unsigned a0, unsigned a1, unsigned & a2)
    { return div_remainder(a0, a1, a2); }

long long intrc___slonglong_div_remainder___slonglong___slonglong___slonglong(long long a0, long long a1, long long & a2)
    { return div_remainder(a0, a1, a2); }

unsigned long long intrc___ulonglong_div_remainder___ulonglong___ulonglong___ulonglong(unsigned long long a0, unsigned long long a1, unsigned long long & a2)
    { return div_remainder(a0, a1, a2); }

void intrc_void_char_memory_copy___P__cchar___P__cchar___sint(volatile char * a0, const volatile char * a1, const int a2)
    { char_memory_copy(a0, a1, a2); }

void intrc_void_short_memory_copy___P__sshort___P__sshort___sint(volatile short * a0, const volatile short * a1, const int a2)
    { short_memory_copy(a0, a1, a2); }

void intrc_void_int_memory_copy___P__sint___P__sint___sint(volatile int * a0, const volatile int * a1, const int a2)
    { int_memory_copy(a0, a1, a2); }

void intrc_void_float_raise___sint(int a0)
    { float_raise(a0); }

int intrc___sint_float32_is_signaling_nan___uint(float32 a0)
    { return float32_is_signaling_nan(a0); }

int intrc___sint_float64_is_signaling_nan_dint(float64 a0)
    { return float64_is_signaling_nan(a0); }

int intrc___sint_f32_to_i32___uint(float32 a0)
    { return f32_to_i32(a0); }

float32 intrc___uint_i32_to_f32___sint(int a0)
    { return i32_to_f32(a0); }

float32 intrc___uint_f32_add___uint___uint(float32 a0, float32 a1)
    { return f32_add(a0, a1); }

float32 intrc___uint_f32_sub___uint___uint(float32 a0, float32 a1)
    { return f32_sub(a0, a1); }

float32 intrc___uint_f32_mul___uint___uint(float32 a0, float32 a1)
    { return f32_mul(a0, a1); }

float32 intrc___uint_f32_div___uint___uint(float32 a0, float32 a1)
    { return f32_div(a0, a1); }

int intrc_bool_f32_le___uint___uint(float32 a0, float32 a1)
    { return f32_le(a0, a1); }

int intrc_bool_f32_lt___uint___uint(float32 a0, float32 a1)
    { return f32_lt(a0, a1); }

int intrc_bool_f32_eq___uint___uint(float32 a0, float32 a1)
    { return f32_eq(a0, a1); }

int intrc___sint_f64_to_i32_dint(float64 a0)
    { return f64_to_i32(a0); }

float64 intrc_dint_i32_to_f64___sint(int a0)
    { return i32_to_f64(a0); }

float64 intrc_dint_f32_to_f64___uint(float32 a0)
    { return f32_to_f64(a0); }

float32 intrc___uint_f64_to_f32_dint(float64 a0)
    { return f64_to_f32(a0); }

float64 intrc_dint_f64_add_dint_dint(float64 a0, float64 a1)
    { return f64_add(a0, a1); }

float64 intrc_dint_f64_sub_dint_dint(float64 a0, float64 a1)
    { return f64_sub(a0, a1); }

float64 intrc_dint_f64_mul_dint_dint(float64 a0, float64 a1)
    { return f64_mul(a0, a1); }

float64 intrc_dint_f64_div_dint_dint(float64 a0, float64 a1)
    { return f64_div(a0, a1); }

int intrc_bool_f64_le_dint_dint(float64 a0, float64 a1)
    { return f64_le(a0, a1); }

int intrc_bool_f64_lt_dint_dint(float64 a0, float64 a1)
    { return f64_lt(a0, a1); }

int intrc_bool_f64_eq_dint_dint(float64 a0, float64 a1)
    { return f64_eq(a0, a1); }

void intrc_void_sha256_ci___uint___uint___uint___uint___uint___uint___uint___uint___uint___uint___uint___uint___uint___uint___uint___uint___uint___uint(unsigned a0, unsigned a1, unsigned a2, unsigned a3, unsigned a4, unsigned a5, unsigned a6, unsigned a7, unsigned a8, unsigned a9, unsigned & a10, unsigned & a11, unsigned & a12, unsigned & a13, unsigned & a14, unsigned & a15, unsigned & a16, unsigned & a17)
    { sha256_ci(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17); }

void intrc_void_sha256_ci___uint___uint___uint___uint___uint___uint___uint___uint___uint___uint(unsigned & a0, unsigned & a1, unsigned & a2, unsigned & a3, unsigned & a4, unsigned & a5, unsigned & a6, unsigned & a7, unsigned a8, unsigned a9)
    { sha256_ci(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9); }

unsigned intrc___uint_sha256_in1___uint___uint___uint___uint(unsigned a0, unsigned a1, unsigned a2, unsigned a3)
    { return sha256_in1(a0, a1, a2, a3); }

unsigned intrc___uint_sha256_in2___uint___uint___uint___uint(unsigned a0, unsigned a1, unsigned a2, unsigned a3)
    { return sha256_in2(a0, a1, a2, a3); }


} //extern "C"  (43 functions)
