
; File generated by darts version N-2018.03#7d02e3ca79#180723, Fri Jan 25 15:45:42 2019
; Copyright 2014-2018 Synopsys, Inc. All rights reserved.
; darts -I/users/Cours/inf8505/12/Documents/inf8505/lab1/tinycore2/labs/lab5/lib +p -d -D__tct_patch__=300 Release/mul_test.o tinycore2

; Release: ipd N-2018.03-SP3
.data_segment_name
.data global 1 a DM
	0xa

.data_segment_name
.data global 1 b DM
	0x6

.data_segment_name
.bss global 1 c DM 1

.text_segment_name
.text global 0 _main
.rela 3 b 0
	/*      0 "10100000000000" */    r0.hi = 0
.rela 3 a 0
	/*      1 "10100000001000" */    r1.hi = 0
.rela 4 b 0
	/*      2 "11000000000000" */    r0 |= 0
.rela 4 a 0
	/*      3 "11000000001000" */    r1 |= 0
	/*      4 "00100000000010" */    r2 = DM[r0]
	/*      5 "00100000001001" */    r1 = DM[r1]
	/*      6 "10000000000011" */    r0 = 3
	/*      7 "01000100001010" */    r1 = r1 * r2
	/*      8 "01000100000001" */    r0 = r0 * r1
.rela 3 c 0
	/*      9 "10100000010000" */    r2.hi = 0
	/*     10 "00101010000000" */    rts
.rela 4 c 0
	/*     11 "11000000010000" */    r2 |= 0
.label _main__end
	/*     12 "00100010010001" */    DM[r2] = r1

.undef global data a

.undef global data b

.undef global data c

