
; File generated by darts version N-2018.03#7d02e3ca79#180723, Fri Jan 25 15:45:43 2019
; Copyright 2014-2018 Synopsys, Inc. All rights reserved.
; darts -I/users/Cours/inf8505/12/Documents/inf8505/lab1/tinycore2/labs/lab5/lib +p -d -D__tct_patch__=300 +u Release/mul_test tinycore2

; Release: ipd N-2018.03-SP3

.text_segment PM      0	   
.entry_point
.label _main
	/*      0      "10100000000000" */    	r0.hi = 0
	/*      1      "10100000001000" */    	r1.hi = 0
	/*      2      "11000000000001" */    	r0 |= 1
	/*      3      "11000000001000" */    	r1 |= 0
	/*      4      "00100000000010" */    	r2 = DM[r0]
	/*      5      "00100000001001" */    	r1 = DM[r1]
	/*      6      "10000000000011" */    	r0 = 3
	/*      7      "01000100001010" */    	r1 = r1 * r2
	/*      8      "01000100000001" */    	r0 = r0 * r1
	/*      9      "10100000010000" */    	r2.hi = 0
	/*     10      "00101010000000" */    	rts
	/*     11      "11000000010010" */    	r2 |= 2
	/*     12      "00100010010001" */    	DM[r2] = r1

.data_segment DM      0	   
.label a
	0xa
.label b
	0x6

.bss_segment DM      2	    1
