
// File generated by noodle version N-2018.03#7d02e3ca79#180723, Fri Jan 11 17:23:01 2019
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// noodle -Pc -B -Iisg +wisg -D__tct_patch__=300 +NOrlt -D__chess__ -D__programmers_view__ tinycore2

// File: builtin_operators.c
// Test C built-in operators  (except any left undefined)
// (Reference in-out argument avoids additional moves i.c.o. read-modify-write)

#ifndef N // arbitrary value, adapt at will
#define N 13
#endif

extern "C" {


} //extern "C"  (0 functions)
