
// File generated by noodle version N-2018.03#7d02e3ca79#180723, Fri Jan 11 17:23:01 2019
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// noodle -Pc -B -Iisg +wisg -D__tct_patch__=300 +NOrlt -D__chess__ -D__programmers_view__ tinycore2

// File: memory_PM.c
// Test memory PM pointer arithmetic stand-alone and with load/store

//!! no load/store instructions found

#ifndef N // arbitrary value, adapt at will
#define N 7
#endif

extern "C" {


} //extern "C"  (0 functions)
