
// File generated by noodle version N-2018.03#7d02e3ca79#180723, Fri Jan 11 17:23:01 2019
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// noodle -Pc -B -Iisg +wisg -D__tct_patch__=300 +NOrlt -D__chess__ -D__programmers_view__ tinycore2

// File: simple_function.c
// Test empty function (return only) and simple function call (without arguments)

extern "C" {

void empty_function() { }

void simple_function_call()
{
    empty_function();  // nested call
    empty_function();  // tail call (may be replaced by jump)
}

//!? no suitable return argument register(s)
//!void indirect_function_call(void (*fnptr)())
//!{
//!    fnptr();  // nested call
//!    fnptr();  // tail call (may be replaced by indirect jump)
//!}


} //extern "C"  (3 functions of which 1 skipped)
