
// File generated by pdg version N-2018.03#7d02e3ca79#180723, Fri Jan 11 16:59:15 2019
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// pdg -P -B -Iisg +wisg -D__tct_patch__=300 -D__checkers__ tinycore2

#include "tinycore2_inline_primitives.h"
namespace tinycore2_primitive {

} // namespace tinycore2_primitive
