
// File generated by noodle version N-2018.03#7d02e3ca79#180723, Fri Jan 11 16:58:52 2019
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// noodle -Pc -B -Iisg +wisg -D__tct_patch__=300 +NOrlt -D__chess__ -D__programmers_view__ tinycore2

#ifdef __chess__
#error "generated native file not intended for compilation by chess"
#endif

#ifndef _tinycore2_chess_opns_h
#define _tinycore2_chess_opns_h

// Native equivalent of Chess promoted operations



// do_generate[_native] inline functions


#endif /*_tinycore2_chess_opns_h*/
