
// File generated by noodle version N-2018.03#7d02e3ca79#180723, Wed Jan 23 12:30:45 2019
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// noodle -Pc -B -Iisg +wisg -I../../io_modules -I/CMC/tools/synopsys/asip_designer_vN-2018.03-SP3/linux64/chessdir/../examples/io_modules -D__tct_patch__=300 -D__chess__ -D__programmers_view__ tlx

// File: memory_KM.c
// Test memory KM pointer arithmetic stand-alone and with load/store

//!! no store instructions found (read only memory)

#ifndef N // arbitrary value, adapt at will
#define N 7
#endif

extern "C" {

//-- signed char                // size=1 alignment=1

void pointer_p1___schar_KM(signed char chess_storage(KM)*& p) { ++p; }
void pointer_m1___schar_KM(signed char chess_storage(KM)*& p) { --p; }
void pointer_pN___schar_KM(signed char chess_storage(KM)*& p) { p += N; }
void pointer_mN___schar_KM(signed char chess_storage(KM)*& p) { p -= N; }
void pointer_pI___schar_KM(signed char chess_storage(KM)*& p, int i) { p += i; }
void pointer_mI___schar_KM(signed char chess_storage(KM)*& p, int i) { p -= i; }

signed char chess_storage(KM) global___schar_KM;
signed char chess_storage(KM) garray___schar_KM[N+1];

signed char load_global___schar_KM() { return global___schar_KM; }
signed char load_garray_pN___schar_KM() { return garray___schar_KM[N]; }
signed char load_garray_pI___schar_KM(int i) { return garray___schar_KM[i]; }

//!void store_global___schar_KM(signed char a) { global___schar_KM = a; }
//!void store_garray_pN___schar_KM(signed char a) { garray___schar_KM[N] = a; }
//!void store_garray_pI___schar_KM(signed char a, int i) { garray___schar_KM[i] = a; }


signed char load_indirect0___schar_KM(signed char chess_storage(KM)* p) { return *p; }
signed char load_indexedp1___schar_KM(signed char chess_storage(KM)* p) { return p[ 1]; }
signed char load_indexedm1___schar_KM(signed char chess_storage(KM)* p) { return p[-1]; }
signed char load_indexedpN___schar_KM(signed char chess_storage(KM)* p) { return p[ N]; }
signed char load_indexedmN___schar_KM(signed char chess_storage(KM)* p) { return p[-N]; }
signed char load_indexedpI___schar_KM(signed char chess_storage(KM)* p, int i) { return p[ i]; }
signed char load_indexedmI___schar_KM(signed char chess_storage(KM)* p, int i) { return p[-i]; }

signed char load_postmodp1___schar_KM(signed char chess_storage(KM)*& p) { return *p++; }
signed char load_postmodm1___schar_KM(signed char chess_storage(KM)*& p) { return *p--; }
signed char load_postmodpN___schar_KM(signed char chess_storage(KM)*& p) { signed char t = *p; p += N; return t; }
signed char load_postmodmN___schar_KM(signed char chess_storage(KM)*& p) { signed char t = *p; p -= N; return t; }
signed char load_postmodpI___schar_KM(signed char chess_storage(KM)*& p, int i) { signed char t = *p; p += i; return t; }
signed char load_postmodmI___schar_KM(signed char chess_storage(KM)*& p, int i) { signed char t = *p; p -= i; return t; }

signed char load_premod_p1___schar_KM(signed char chess_storage(KM)*& p) { return *++p; }
signed char load_premod_m1___schar_KM(signed char chess_storage(KM)*& p) { return *--p; }
signed char load_premod_pN___schar_KM(signed char chess_storage(KM)*& p) { p += N; return *p; }
signed char load_premod_mN___schar_KM(signed char chess_storage(KM)*& p) { p -= N; return *p; }
signed char load_premod_pI___schar_KM(signed char chess_storage(KM)*& p, int i) { p += i; return *p; }
signed char load_premod_mI___schar_KM(signed char chess_storage(KM)*& p, int i) { p -= i; return *p; }

//!void store_indirect0___schar_KM(signed char a, signed char chess_storage(KM)* p) { *p = a; }
//!void store_indexedp1___schar_KM(signed char a, signed char chess_storage(KM)* p) { p[ 1] = a; }
//!void store_indexedm1___schar_KM(signed char a, signed char chess_storage(KM)* p) { p[-1] = a; }
//!void store_indexedpN___schar_KM(signed char a, signed char chess_storage(KM)* p) { p[ N] = a; }
//!void store_indexedmN___schar_KM(signed char a, signed char chess_storage(KM)* p) { p[-N] = a; }
//!void store_indexedpI___schar_KM(signed char a, signed char chess_storage(KM)* p, int i) { p[ i] = a; }
//!void store_indexedmI___schar_KM(signed char a, signed char chess_storage(KM)* p, int i) { p[-i] = a; }

//!void store_postmodp1___schar_KM(signed char a, signed char chess_storage(KM)*& p) { *p++ = a; }
//!void store_postmodm1___schar_KM(signed char a, signed char chess_storage(KM)*& p) { *p-- = a; }
//!void store_postmodpN___schar_KM(signed char a, signed char chess_storage(KM)*& p) { *p = a; p += N; }
//!void store_postmodmN___schar_KM(signed char a, signed char chess_storage(KM)*& p) { *p = a; p -= N; }
//!void store_postmodpI___schar_KM(signed char a, signed char chess_storage(KM)*& p, int i) { *p = a; p += i; }
//!void store_postmodmI___schar_KM(signed char a, signed char chess_storage(KM)*& p, int i) { *p = a; p -= i; }

//!void store_premod_p1___schar_KM(signed char a, signed char chess_storage(KM)*& p) { *++p = a; }
//!void store_premod_m1___schar_KM(signed char a, signed char chess_storage(KM)*& p) { *--p = a; }
//!void store_premod_pN___schar_KM(signed char a, signed char chess_storage(KM)*& p) { p += N; *p = a; }
//!void store_premod_mN___schar_KM(signed char a, signed char chess_storage(KM)*& p) { p -= N; *p = a; }
//!void store_premod_pI___schar_KM(signed char a, signed char chess_storage(KM)*& p, int i) { p += i; *p = a; }
//!void store_premod_mI___schar_KM(signed char a, signed char chess_storage(KM)*& p, int i) { p -= i; *p = a; }

//-- unsigned char              // size=1 alignment=1

void pointer_p1___uchar_KM(unsigned char chess_storage(KM)*& p) { ++p; }
void pointer_m1___uchar_KM(unsigned char chess_storage(KM)*& p) { --p; }
void pointer_pN___uchar_KM(unsigned char chess_storage(KM)*& p) { p += N; }
void pointer_mN___uchar_KM(unsigned char chess_storage(KM)*& p) { p -= N; }
void pointer_pI___uchar_KM(unsigned char chess_storage(KM)*& p, int i) { p += i; }
void pointer_mI___uchar_KM(unsigned char chess_storage(KM)*& p, int i) { p -= i; }

unsigned char chess_storage(KM) global___uchar_KM;
unsigned char chess_storage(KM) garray___uchar_KM[N+1];

unsigned char load_global___uchar_KM() { return global___uchar_KM; }
unsigned char load_garray_pN___uchar_KM() { return garray___uchar_KM[N]; }
unsigned char load_garray_pI___uchar_KM(int i) { return garray___uchar_KM[i]; }

//!void store_global___uchar_KM(unsigned char a) { global___uchar_KM = a; }
//!void store_garray_pN___uchar_KM(unsigned char a) { garray___uchar_KM[N] = a; }
//!void store_garray_pI___uchar_KM(unsigned char a, int i) { garray___uchar_KM[i] = a; }


unsigned char load_indirect0___uchar_KM(unsigned char chess_storage(KM)* p) { return *p; }
unsigned char load_indexedp1___uchar_KM(unsigned char chess_storage(KM)* p) { return p[ 1]; }
unsigned char load_indexedm1___uchar_KM(unsigned char chess_storage(KM)* p) { return p[-1]; }
unsigned char load_indexedpN___uchar_KM(unsigned char chess_storage(KM)* p) { return p[ N]; }
unsigned char load_indexedmN___uchar_KM(unsigned char chess_storage(KM)* p) { return p[-N]; }
unsigned char load_indexedpI___uchar_KM(unsigned char chess_storage(KM)* p, int i) { return p[ i]; }
unsigned char load_indexedmI___uchar_KM(unsigned char chess_storage(KM)* p, int i) { return p[-i]; }

unsigned char load_postmodp1___uchar_KM(unsigned char chess_storage(KM)*& p) { return *p++; }
unsigned char load_postmodm1___uchar_KM(unsigned char chess_storage(KM)*& p) { return *p--; }
unsigned char load_postmodpN___uchar_KM(unsigned char chess_storage(KM)*& p) { unsigned char t = *p; p += N; return t; }
unsigned char load_postmodmN___uchar_KM(unsigned char chess_storage(KM)*& p) { unsigned char t = *p; p -= N; return t; }
unsigned char load_postmodpI___uchar_KM(unsigned char chess_storage(KM)*& p, int i) { unsigned char t = *p; p += i; return t; }
unsigned char load_postmodmI___uchar_KM(unsigned char chess_storage(KM)*& p, int i) { unsigned char t = *p; p -= i; return t; }

unsigned char load_premod_p1___uchar_KM(unsigned char chess_storage(KM)*& p) { return *++p; }
unsigned char load_premod_m1___uchar_KM(unsigned char chess_storage(KM)*& p) { return *--p; }
unsigned char load_premod_pN___uchar_KM(unsigned char chess_storage(KM)*& p) { p += N; return *p; }
unsigned char load_premod_mN___uchar_KM(unsigned char chess_storage(KM)*& p) { p -= N; return *p; }
unsigned char load_premod_pI___uchar_KM(unsigned char chess_storage(KM)*& p, int i) { p += i; return *p; }
unsigned char load_premod_mI___uchar_KM(unsigned char chess_storage(KM)*& p, int i) { p -= i; return *p; }

//!void store_indirect0___uchar_KM(unsigned char a, unsigned char chess_storage(KM)* p) { *p = a; }
//!void store_indexedp1___uchar_KM(unsigned char a, unsigned char chess_storage(KM)* p) { p[ 1] = a; }
//!void store_indexedm1___uchar_KM(unsigned char a, unsigned char chess_storage(KM)* p) { p[-1] = a; }
//!void store_indexedpN___uchar_KM(unsigned char a, unsigned char chess_storage(KM)* p) { p[ N] = a; }
//!void store_indexedmN___uchar_KM(unsigned char a, unsigned char chess_storage(KM)* p) { p[-N] = a; }
//!void store_indexedpI___uchar_KM(unsigned char a, unsigned char chess_storage(KM)* p, int i) { p[ i] = a; }
//!void store_indexedmI___uchar_KM(unsigned char a, unsigned char chess_storage(KM)* p, int i) { p[-i] = a; }

//!void store_postmodp1___uchar_KM(unsigned char a, unsigned char chess_storage(KM)*& p) { *p++ = a; }
//!void store_postmodm1___uchar_KM(unsigned char a, unsigned char chess_storage(KM)*& p) { *p-- = a; }
//!void store_postmodpN___uchar_KM(unsigned char a, unsigned char chess_storage(KM)*& p) { *p = a; p += N; }
//!void store_postmodmN___uchar_KM(unsigned char a, unsigned char chess_storage(KM)*& p) { *p = a; p -= N; }
//!void store_postmodpI___uchar_KM(unsigned char a, unsigned char chess_storage(KM)*& p, int i) { *p = a; p += i; }
//!void store_postmodmI___uchar_KM(unsigned char a, unsigned char chess_storage(KM)*& p, int i) { *p = a; p -= i; }

//!void store_premod_p1___uchar_KM(unsigned char a, unsigned char chess_storage(KM)*& p) { *++p = a; }
//!void store_premod_m1___uchar_KM(unsigned char a, unsigned char chess_storage(KM)*& p) { *--p = a; }
//!void store_premod_pN___uchar_KM(unsigned char a, unsigned char chess_storage(KM)*& p) { p += N; *p = a; }
//!void store_premod_mN___uchar_KM(unsigned char a, unsigned char chess_storage(KM)*& p) { p -= N; *p = a; }
//!void store_premod_pI___uchar_KM(unsigned char a, unsigned char chess_storage(KM)*& p, int i) { p += i; *p = a; }
//!void store_premod_mI___uchar_KM(unsigned char a, unsigned char chess_storage(KM)*& p, int i) { p -= i; *p = a; }

//-- short                      // size=1 alignment=1

void pointer_p1___sshort_KM(short chess_storage(KM)*& p) { ++p; }
void pointer_m1___sshort_KM(short chess_storage(KM)*& p) { --p; }
void pointer_pN___sshort_KM(short chess_storage(KM)*& p) { p += N; }
void pointer_mN___sshort_KM(short chess_storage(KM)*& p) { p -= N; }
void pointer_pI___sshort_KM(short chess_storage(KM)*& p, int i) { p += i; }
void pointer_mI___sshort_KM(short chess_storage(KM)*& p, int i) { p -= i; }

short chess_storage(KM) global___sshort_KM;
short chess_storage(KM) garray___sshort_KM[N+1];

short load_global___sshort_KM() { return global___sshort_KM; }
short load_garray_pN___sshort_KM() { return garray___sshort_KM[N]; }
short load_garray_pI___sshort_KM(int i) { return garray___sshort_KM[i]; }

//!void store_global___sshort_KM(short a) { global___sshort_KM = a; }
//!void store_garray_pN___sshort_KM(short a) { garray___sshort_KM[N] = a; }
//!void store_garray_pI___sshort_KM(short a, int i) { garray___sshort_KM[i] = a; }


short load_indirect0___sshort_KM(short chess_storage(KM)* p) { return *p; }
short load_indexedp1___sshort_KM(short chess_storage(KM)* p) { return p[ 1]; }
short load_indexedm1___sshort_KM(short chess_storage(KM)* p) { return p[-1]; }
short load_indexedpN___sshort_KM(short chess_storage(KM)* p) { return p[ N]; }
short load_indexedmN___sshort_KM(short chess_storage(KM)* p) { return p[-N]; }
short load_indexedpI___sshort_KM(short chess_storage(KM)* p, int i) { return p[ i]; }
short load_indexedmI___sshort_KM(short chess_storage(KM)* p, int i) { return p[-i]; }

short load_postmodp1___sshort_KM(short chess_storage(KM)*& p) { return *p++; }
short load_postmodm1___sshort_KM(short chess_storage(KM)*& p) { return *p--; }
short load_postmodpN___sshort_KM(short chess_storage(KM)*& p) { short t = *p; p += N; return t; }
short load_postmodmN___sshort_KM(short chess_storage(KM)*& p) { short t = *p; p -= N; return t; }
short load_postmodpI___sshort_KM(short chess_storage(KM)*& p, int i) { short t = *p; p += i; return t; }
short load_postmodmI___sshort_KM(short chess_storage(KM)*& p, int i) { short t = *p; p -= i; return t; }

short load_premod_p1___sshort_KM(short chess_storage(KM)*& p) { return *++p; }
short load_premod_m1___sshort_KM(short chess_storage(KM)*& p) { return *--p; }
short load_premod_pN___sshort_KM(short chess_storage(KM)*& p) { p += N; return *p; }
short load_premod_mN___sshort_KM(short chess_storage(KM)*& p) { p -= N; return *p; }
short load_premod_pI___sshort_KM(short chess_storage(KM)*& p, int i) { p += i; return *p; }
short load_premod_mI___sshort_KM(short chess_storage(KM)*& p, int i) { p -= i; return *p; }

//!void store_indirect0___sshort_KM(short a, short chess_storage(KM)* p) { *p = a; }
//!void store_indexedp1___sshort_KM(short a, short chess_storage(KM)* p) { p[ 1] = a; }
//!void store_indexedm1___sshort_KM(short a, short chess_storage(KM)* p) { p[-1] = a; }
//!void store_indexedpN___sshort_KM(short a, short chess_storage(KM)* p) { p[ N] = a; }
//!void store_indexedmN___sshort_KM(short a, short chess_storage(KM)* p) { p[-N] = a; }
//!void store_indexedpI___sshort_KM(short a, short chess_storage(KM)* p, int i) { p[ i] = a; }
//!void store_indexedmI___sshort_KM(short a, short chess_storage(KM)* p, int i) { p[-i] = a; }

//!void store_postmodp1___sshort_KM(short a, short chess_storage(KM)*& p) { *p++ = a; }
//!void store_postmodm1___sshort_KM(short a, short chess_storage(KM)*& p) { *p-- = a; }
//!void store_postmodpN___sshort_KM(short a, short chess_storage(KM)*& p) { *p = a; p += N; }
//!void store_postmodmN___sshort_KM(short a, short chess_storage(KM)*& p) { *p = a; p -= N; }
//!void store_postmodpI___sshort_KM(short a, short chess_storage(KM)*& p, int i) { *p = a; p += i; }
//!void store_postmodmI___sshort_KM(short a, short chess_storage(KM)*& p, int i) { *p = a; p -= i; }

//!void store_premod_p1___sshort_KM(short a, short chess_storage(KM)*& p) { *++p = a; }
//!void store_premod_m1___sshort_KM(short a, short chess_storage(KM)*& p) { *--p = a; }
//!void store_premod_pN___sshort_KM(short a, short chess_storage(KM)*& p) { p += N; *p = a; }
//!void store_premod_mN___sshort_KM(short a, short chess_storage(KM)*& p) { p -= N; *p = a; }
//!void store_premod_pI___sshort_KM(short a, short chess_storage(KM)*& p, int i) { p += i; *p = a; }
//!void store_premod_mI___sshort_KM(short a, short chess_storage(KM)*& p, int i) { p -= i; *p = a; }

//-- unsigned short             // size=1 alignment=1

void pointer_p1___ushort_KM(unsigned short chess_storage(KM)*& p) { ++p; }
void pointer_m1___ushort_KM(unsigned short chess_storage(KM)*& p) { --p; }
void pointer_pN___ushort_KM(unsigned short chess_storage(KM)*& p) { p += N; }
void pointer_mN___ushort_KM(unsigned short chess_storage(KM)*& p) { p -= N; }
void pointer_pI___ushort_KM(unsigned short chess_storage(KM)*& p, int i) { p += i; }
void pointer_mI___ushort_KM(unsigned short chess_storage(KM)*& p, int i) { p -= i; }

unsigned short chess_storage(KM) global___ushort_KM;
unsigned short chess_storage(KM) garray___ushort_KM[N+1];

unsigned short load_global___ushort_KM() { return global___ushort_KM; }
unsigned short load_garray_pN___ushort_KM() { return garray___ushort_KM[N]; }
unsigned short load_garray_pI___ushort_KM(int i) { return garray___ushort_KM[i]; }

//!void store_global___ushort_KM(unsigned short a) { global___ushort_KM = a; }
//!void store_garray_pN___ushort_KM(unsigned short a) { garray___ushort_KM[N] = a; }
//!void store_garray_pI___ushort_KM(unsigned short a, int i) { garray___ushort_KM[i] = a; }


unsigned short load_indirect0___ushort_KM(unsigned short chess_storage(KM)* p) { return *p; }
unsigned short load_indexedp1___ushort_KM(unsigned short chess_storage(KM)* p) { return p[ 1]; }
unsigned short load_indexedm1___ushort_KM(unsigned short chess_storage(KM)* p) { return p[-1]; }
unsigned short load_indexedpN___ushort_KM(unsigned short chess_storage(KM)* p) { return p[ N]; }
unsigned short load_indexedmN___ushort_KM(unsigned short chess_storage(KM)* p) { return p[-N]; }
unsigned short load_indexedpI___ushort_KM(unsigned short chess_storage(KM)* p, int i) { return p[ i]; }
unsigned short load_indexedmI___ushort_KM(unsigned short chess_storage(KM)* p, int i) { return p[-i]; }

unsigned short load_postmodp1___ushort_KM(unsigned short chess_storage(KM)*& p) { return *p++; }
unsigned short load_postmodm1___ushort_KM(unsigned short chess_storage(KM)*& p) { return *p--; }
unsigned short load_postmodpN___ushort_KM(unsigned short chess_storage(KM)*& p) { unsigned short t = *p; p += N; return t; }
unsigned short load_postmodmN___ushort_KM(unsigned short chess_storage(KM)*& p) { unsigned short t = *p; p -= N; return t; }
unsigned short load_postmodpI___ushort_KM(unsigned short chess_storage(KM)*& p, int i) { unsigned short t = *p; p += i; return t; }
unsigned short load_postmodmI___ushort_KM(unsigned short chess_storage(KM)*& p, int i) { unsigned short t = *p; p -= i; return t; }

unsigned short load_premod_p1___ushort_KM(unsigned short chess_storage(KM)*& p) { return *++p; }
unsigned short load_premod_m1___ushort_KM(unsigned short chess_storage(KM)*& p) { return *--p; }
unsigned short load_premod_pN___ushort_KM(unsigned short chess_storage(KM)*& p) { p += N; return *p; }
unsigned short load_premod_mN___ushort_KM(unsigned short chess_storage(KM)*& p) { p -= N; return *p; }
unsigned short load_premod_pI___ushort_KM(unsigned short chess_storage(KM)*& p, int i) { p += i; return *p; }
unsigned short load_premod_mI___ushort_KM(unsigned short chess_storage(KM)*& p, int i) { p -= i; return *p; }

//!void store_indirect0___ushort_KM(unsigned short a, unsigned short chess_storage(KM)* p) { *p = a; }
//!void store_indexedp1___ushort_KM(unsigned short a, unsigned short chess_storage(KM)* p) { p[ 1] = a; }
//!void store_indexedm1___ushort_KM(unsigned short a, unsigned short chess_storage(KM)* p) { p[-1] = a; }
//!void store_indexedpN___ushort_KM(unsigned short a, unsigned short chess_storage(KM)* p) { p[ N] = a; }
//!void store_indexedmN___ushort_KM(unsigned short a, unsigned short chess_storage(KM)* p) { p[-N] = a; }
//!void store_indexedpI___ushort_KM(unsigned short a, unsigned short chess_storage(KM)* p, int i) { p[ i] = a; }
//!void store_indexedmI___ushort_KM(unsigned short a, unsigned short chess_storage(KM)* p, int i) { p[-i] = a; }

//!void store_postmodp1___ushort_KM(unsigned short a, unsigned short chess_storage(KM)*& p) { *p++ = a; }
//!void store_postmodm1___ushort_KM(unsigned short a, unsigned short chess_storage(KM)*& p) { *p-- = a; }
//!void store_postmodpN___ushort_KM(unsigned short a, unsigned short chess_storage(KM)*& p) { *p = a; p += N; }
//!void store_postmodmN___ushort_KM(unsigned short a, unsigned short chess_storage(KM)*& p) { *p = a; p -= N; }
//!void store_postmodpI___ushort_KM(unsigned short a, unsigned short chess_storage(KM)*& p, int i) { *p = a; p += i; }
//!void store_postmodmI___ushort_KM(unsigned short a, unsigned short chess_storage(KM)*& p, int i) { *p = a; p -= i; }

//!void store_premod_p1___ushort_KM(unsigned short a, unsigned short chess_storage(KM)*& p) { *++p = a; }
//!void store_premod_m1___ushort_KM(unsigned short a, unsigned short chess_storage(KM)*& p) { *--p = a; }
//!void store_premod_pN___ushort_KM(unsigned short a, unsigned short chess_storage(KM)*& p) { p += N; *p = a; }
//!void store_premod_mN___ushort_KM(unsigned short a, unsigned short chess_storage(KM)*& p) { p -= N; *p = a; }
//!void store_premod_pI___ushort_KM(unsigned short a, unsigned short chess_storage(KM)*& p, int i) { p += i; *p = a; }
//!void store_premod_mI___ushort_KM(unsigned short a, unsigned short chess_storage(KM)*& p, int i) { p -= i; *p = a; }

//-- int                        // size=1 alignment=1

void pointer_p1___sint_KM(int chess_storage(KM)*& p) { ++p; }
void pointer_m1___sint_KM(int chess_storage(KM)*& p) { --p; }
void pointer_pN___sint_KM(int chess_storage(KM)*& p) { p += N; }
void pointer_mN___sint_KM(int chess_storage(KM)*& p) { p -= N; }
void pointer_pI___sint_KM(int chess_storage(KM)*& p, int i) { p += i; }
void pointer_mI___sint_KM(int chess_storage(KM)*& p, int i) { p -= i; }

int chess_storage(KM) global___sint_KM;
int chess_storage(KM) garray___sint_KM[N+1];

int load_global___sint_KM() { return global___sint_KM; }
int load_garray_pN___sint_KM() { return garray___sint_KM[N]; }
int load_garray_pI___sint_KM(int i) { return garray___sint_KM[i]; }

//!void store_global___sint_KM(int a) { global___sint_KM = a; }
//!void store_garray_pN___sint_KM(int a) { garray___sint_KM[N] = a; }
//!void store_garray_pI___sint_KM(int a, int i) { garray___sint_KM[i] = a; }


int load_indirect0___sint_KM(int chess_storage(KM)* p) { return *p; }
int load_indexedp1___sint_KM(int chess_storage(KM)* p) { return p[ 1]; }
int load_indexedm1___sint_KM(int chess_storage(KM)* p) { return p[-1]; }
int load_indexedpN___sint_KM(int chess_storage(KM)* p) { return p[ N]; }
int load_indexedmN___sint_KM(int chess_storage(KM)* p) { return p[-N]; }
int load_indexedpI___sint_KM(int chess_storage(KM)* p, int i) { return p[ i]; }
int load_indexedmI___sint_KM(int chess_storage(KM)* p, int i) { return p[-i]; }

int load_postmodp1___sint_KM(int chess_storage(KM)*& p) { return *p++; }
int load_postmodm1___sint_KM(int chess_storage(KM)*& p) { return *p--; }
int load_postmodpN___sint_KM(int chess_storage(KM)*& p) { int t = *p; p += N; return t; }
int load_postmodmN___sint_KM(int chess_storage(KM)*& p) { int t = *p; p -= N; return t; }
int load_postmodpI___sint_KM(int chess_storage(KM)*& p, int i) { int t = *p; p += i; return t; }
int load_postmodmI___sint_KM(int chess_storage(KM)*& p, int i) { int t = *p; p -= i; return t; }

int load_premod_p1___sint_KM(int chess_storage(KM)*& p) { return *++p; }
int load_premod_m1___sint_KM(int chess_storage(KM)*& p) { return *--p; }
int load_premod_pN___sint_KM(int chess_storage(KM)*& p) { p += N; return *p; }
int load_premod_mN___sint_KM(int chess_storage(KM)*& p) { p -= N; return *p; }
int load_premod_pI___sint_KM(int chess_storage(KM)*& p, int i) { p += i; return *p; }
int load_premod_mI___sint_KM(int chess_storage(KM)*& p, int i) { p -= i; return *p; }

//!void store_indirect0___sint_KM(int a, int chess_storage(KM)* p) { *p = a; }
//!void store_indexedp1___sint_KM(int a, int chess_storage(KM)* p) { p[ 1] = a; }
//!void store_indexedm1___sint_KM(int a, int chess_storage(KM)* p) { p[-1] = a; }
//!void store_indexedpN___sint_KM(int a, int chess_storage(KM)* p) { p[ N] = a; }
//!void store_indexedmN___sint_KM(int a, int chess_storage(KM)* p) { p[-N] = a; }
//!void store_indexedpI___sint_KM(int a, int chess_storage(KM)* p, int i) { p[ i] = a; }
//!void store_indexedmI___sint_KM(int a, int chess_storage(KM)* p, int i) { p[-i] = a; }

//!void store_postmodp1___sint_KM(int a, int chess_storage(KM)*& p) { *p++ = a; }
//!void store_postmodm1___sint_KM(int a, int chess_storage(KM)*& p) { *p-- = a; }
//!void store_postmodpN___sint_KM(int a, int chess_storage(KM)*& p) { *p = a; p += N; }
//!void store_postmodmN___sint_KM(int a, int chess_storage(KM)*& p) { *p = a; p -= N; }
//!void store_postmodpI___sint_KM(int a, int chess_storage(KM)*& p, int i) { *p = a; p += i; }
//!void store_postmodmI___sint_KM(int a, int chess_storage(KM)*& p, int i) { *p = a; p -= i; }

//!void store_premod_p1___sint_KM(int a, int chess_storage(KM)*& p) { *++p = a; }
//!void store_premod_m1___sint_KM(int a, int chess_storage(KM)*& p) { *--p = a; }
//!void store_premod_pN___sint_KM(int a, int chess_storage(KM)*& p) { p += N; *p = a; }
//!void store_premod_mN___sint_KM(int a, int chess_storage(KM)*& p) { p -= N; *p = a; }
//!void store_premod_pI___sint_KM(int a, int chess_storage(KM)*& p, int i) { p += i; *p = a; }
//!void store_premod_mI___sint_KM(int a, int chess_storage(KM)*& p, int i) { p -= i; *p = a; }

//-- unsigned                   // size=1 alignment=1

void pointer_p1___uint_KM(unsigned chess_storage(KM)*& p) { ++p; }
void pointer_m1___uint_KM(unsigned chess_storage(KM)*& p) { --p; }
void pointer_pN___uint_KM(unsigned chess_storage(KM)*& p) { p += N; }
void pointer_mN___uint_KM(unsigned chess_storage(KM)*& p) { p -= N; }
void pointer_pI___uint_KM(unsigned chess_storage(KM)*& p, int i) { p += i; }
void pointer_mI___uint_KM(unsigned chess_storage(KM)*& p, int i) { p -= i; }

unsigned chess_storage(KM) global___uint_KM;
unsigned chess_storage(KM) garray___uint_KM[N+1];

unsigned load_global___uint_KM() { return global___uint_KM; }
unsigned load_garray_pN___uint_KM() { return garray___uint_KM[N]; }
unsigned load_garray_pI___uint_KM(int i) { return garray___uint_KM[i]; }

//!void store_global___uint_KM(unsigned a) { global___uint_KM = a; }
//!void store_garray_pN___uint_KM(unsigned a) { garray___uint_KM[N] = a; }
//!void store_garray_pI___uint_KM(unsigned a, int i) { garray___uint_KM[i] = a; }


unsigned load_indirect0___uint_KM(unsigned chess_storage(KM)* p) { return *p; }
unsigned load_indexedp1___uint_KM(unsigned chess_storage(KM)* p) { return p[ 1]; }
unsigned load_indexedm1___uint_KM(unsigned chess_storage(KM)* p) { return p[-1]; }
unsigned load_indexedpN___uint_KM(unsigned chess_storage(KM)* p) { return p[ N]; }
unsigned load_indexedmN___uint_KM(unsigned chess_storage(KM)* p) { return p[-N]; }
unsigned load_indexedpI___uint_KM(unsigned chess_storage(KM)* p, int i) { return p[ i]; }
unsigned load_indexedmI___uint_KM(unsigned chess_storage(KM)* p, int i) { return p[-i]; }

unsigned load_postmodp1___uint_KM(unsigned chess_storage(KM)*& p) { return *p++; }
unsigned load_postmodm1___uint_KM(unsigned chess_storage(KM)*& p) { return *p--; }
unsigned load_postmodpN___uint_KM(unsigned chess_storage(KM)*& p) { unsigned t = *p; p += N; return t; }
unsigned load_postmodmN___uint_KM(unsigned chess_storage(KM)*& p) { unsigned t = *p; p -= N; return t; }
unsigned load_postmodpI___uint_KM(unsigned chess_storage(KM)*& p, int i) { unsigned t = *p; p += i; return t; }
unsigned load_postmodmI___uint_KM(unsigned chess_storage(KM)*& p, int i) { unsigned t = *p; p -= i; return t; }

unsigned load_premod_p1___uint_KM(unsigned chess_storage(KM)*& p) { return *++p; }
unsigned load_premod_m1___uint_KM(unsigned chess_storage(KM)*& p) { return *--p; }
unsigned load_premod_pN___uint_KM(unsigned chess_storage(KM)*& p) { p += N; return *p; }
unsigned load_premod_mN___uint_KM(unsigned chess_storage(KM)*& p) { p -= N; return *p; }
unsigned load_premod_pI___uint_KM(unsigned chess_storage(KM)*& p, int i) { p += i; return *p; }
unsigned load_premod_mI___uint_KM(unsigned chess_storage(KM)*& p, int i) { p -= i; return *p; }

//!void store_indirect0___uint_KM(unsigned a, unsigned chess_storage(KM)* p) { *p = a; }
//!void store_indexedp1___uint_KM(unsigned a, unsigned chess_storage(KM)* p) { p[ 1] = a; }
//!void store_indexedm1___uint_KM(unsigned a, unsigned chess_storage(KM)* p) { p[-1] = a; }
//!void store_indexedpN___uint_KM(unsigned a, unsigned chess_storage(KM)* p) { p[ N] = a; }
//!void store_indexedmN___uint_KM(unsigned a, unsigned chess_storage(KM)* p) { p[-N] = a; }
//!void store_indexedpI___uint_KM(unsigned a, unsigned chess_storage(KM)* p, int i) { p[ i] = a; }
//!void store_indexedmI___uint_KM(unsigned a, unsigned chess_storage(KM)* p, int i) { p[-i] = a; }

//!void store_postmodp1___uint_KM(unsigned a, unsigned chess_storage(KM)*& p) { *p++ = a; }
//!void store_postmodm1___uint_KM(unsigned a, unsigned chess_storage(KM)*& p) { *p-- = a; }
//!void store_postmodpN___uint_KM(unsigned a, unsigned chess_storage(KM)*& p) { *p = a; p += N; }
//!void store_postmodmN___uint_KM(unsigned a, unsigned chess_storage(KM)*& p) { *p = a; p -= N; }
//!void store_postmodpI___uint_KM(unsigned a, unsigned chess_storage(KM)*& p, int i) { *p = a; p += i; }
//!void store_postmodmI___uint_KM(unsigned a, unsigned chess_storage(KM)*& p, int i) { *p = a; p -= i; }

//!void store_premod_p1___uint_KM(unsigned a, unsigned chess_storage(KM)*& p) { *++p = a; }
//!void store_premod_m1___uint_KM(unsigned a, unsigned chess_storage(KM)*& p) { *--p = a; }
//!void store_premod_pN___uint_KM(unsigned a, unsigned chess_storage(KM)*& p) { p += N; *p = a; }
//!void store_premod_mN___uint_KM(unsigned a, unsigned chess_storage(KM)*& p) { p -= N; *p = a; }
//!void store_premod_pI___uint_KM(unsigned a, unsigned chess_storage(KM)*& p, int i) { p += i; *p = a; }
//!void store_premod_mI___uint_KM(unsigned a, unsigned chess_storage(KM)*& p, int i) { p -= i; *p = a; }

//-- long long                  // size=2 alignment=1

void pointer_p1___slonglong_KM(long long chess_storage(KM)*& p) { ++p; }
void pointer_m1___slonglong_KM(long long chess_storage(KM)*& p) { --p; }
void pointer_pN___slonglong_KM(long long chess_storage(KM)*& p) { p += N; }
void pointer_mN___slonglong_KM(long long chess_storage(KM)*& p) { p -= N; }
void pointer_pI___slonglong_KM(long long chess_storage(KM)*& p, int i) { p += i; }
void pointer_mI___slonglong_KM(long long chess_storage(KM)*& p, int i) { p -= i; }

long long chess_storage(KM) global___slonglong_KM;
long long chess_storage(KM) garray___slonglong_KM[N+1];

long long load_global___slonglong_KM() { return global___slonglong_KM; }
long long load_garray_pN___slonglong_KM() { return garray___slonglong_KM[N]; }
long long load_garray_pI___slonglong_KM(int i) { return garray___slonglong_KM[i]; }

//!void store_global___slonglong_KM(long long a) { global___slonglong_KM = a; }
//!void store_garray_pN___slonglong_KM(long long a) { garray___slonglong_KM[N] = a; }
//!void store_garray_pI___slonglong_KM(long long a, int i) { garray___slonglong_KM[i] = a; }


long long load_indirect0___slonglong_KM(long long chess_storage(KM)* p) { return *p; }
long long load_indexedp1___slonglong_KM(long long chess_storage(KM)* p) { return p[ 1]; }
long long load_indexedm1___slonglong_KM(long long chess_storage(KM)* p) { return p[-1]; }
long long load_indexedpN___slonglong_KM(long long chess_storage(KM)* p) { return p[ N]; }
long long load_indexedmN___slonglong_KM(long long chess_storage(KM)* p) { return p[-N]; }
long long load_indexedpI___slonglong_KM(long long chess_storage(KM)* p, int i) { return p[ i]; }
long long load_indexedmI___slonglong_KM(long long chess_storage(KM)* p, int i) { return p[-i]; }

long long load_postmodp1___slonglong_KM(long long chess_storage(KM)*& p) { return *p++; }
long long load_postmodm1___slonglong_KM(long long chess_storage(KM)*& p) { return *p--; }
long long load_postmodpN___slonglong_KM(long long chess_storage(KM)*& p) { long long t = *p; p += N; return t; }
long long load_postmodmN___slonglong_KM(long long chess_storage(KM)*& p) { long long t = *p; p -= N; return t; }
long long load_postmodpI___slonglong_KM(long long chess_storage(KM)*& p, int i) { long long t = *p; p += i; return t; }
long long load_postmodmI___slonglong_KM(long long chess_storage(KM)*& p, int i) { long long t = *p; p -= i; return t; }

long long load_premod_p1___slonglong_KM(long long chess_storage(KM)*& p) { return *++p; }
long long load_premod_m1___slonglong_KM(long long chess_storage(KM)*& p) { return *--p; }
long long load_premod_pN___slonglong_KM(long long chess_storage(KM)*& p) { p += N; return *p; }
long long load_premod_mN___slonglong_KM(long long chess_storage(KM)*& p) { p -= N; return *p; }
long long load_premod_pI___slonglong_KM(long long chess_storage(KM)*& p, int i) { p += i; return *p; }
long long load_premod_mI___slonglong_KM(long long chess_storage(KM)*& p, int i) { p -= i; return *p; }

//!void store_indirect0___slonglong_KM(long long a, long long chess_storage(KM)* p) { *p = a; }
//!void store_indexedp1___slonglong_KM(long long a, long long chess_storage(KM)* p) { p[ 1] = a; }
//!void store_indexedm1___slonglong_KM(long long a, long long chess_storage(KM)* p) { p[-1] = a; }
//!void store_indexedpN___slonglong_KM(long long a, long long chess_storage(KM)* p) { p[ N] = a; }
//!void store_indexedmN___slonglong_KM(long long a, long long chess_storage(KM)* p) { p[-N] = a; }
//!void store_indexedpI___slonglong_KM(long long a, long long chess_storage(KM)* p, int i) { p[ i] = a; }
//!void store_indexedmI___slonglong_KM(long long a, long long chess_storage(KM)* p, int i) { p[-i] = a; }

//!void store_postmodp1___slonglong_KM(long long a, long long chess_storage(KM)*& p) { *p++ = a; }
//!void store_postmodm1___slonglong_KM(long long a, long long chess_storage(KM)*& p) { *p-- = a; }
//!void store_postmodpN___slonglong_KM(long long a, long long chess_storage(KM)*& p) { *p = a; p += N; }
//!void store_postmodmN___slonglong_KM(long long a, long long chess_storage(KM)*& p) { *p = a; p -= N; }
//!void store_postmodpI___slonglong_KM(long long a, long long chess_storage(KM)*& p, int i) { *p = a; p += i; }
//!void store_postmodmI___slonglong_KM(long long a, long long chess_storage(KM)*& p, int i) { *p = a; p -= i; }

//!void store_premod_p1___slonglong_KM(long long a, long long chess_storage(KM)*& p) { *++p = a; }
//!void store_premod_m1___slonglong_KM(long long a, long long chess_storage(KM)*& p) { *--p = a; }
//!void store_premod_pN___slonglong_KM(long long a, long long chess_storage(KM)*& p) { p += N; *p = a; }
//!void store_premod_mN___slonglong_KM(long long a, long long chess_storage(KM)*& p) { p -= N; *p = a; }
//!void store_premod_pI___slonglong_KM(long long a, long long chess_storage(KM)*& p, int i) { p += i; *p = a; }
//!void store_premod_mI___slonglong_KM(long long a, long long chess_storage(KM)*& p, int i) { p -= i; *p = a; }

//-- unsigned long long         // size=2 alignment=1

void pointer_p1___ulonglong_KM(unsigned long long chess_storage(KM)*& p) { ++p; }
void pointer_m1___ulonglong_KM(unsigned long long chess_storage(KM)*& p) { --p; }
void pointer_pN___ulonglong_KM(unsigned long long chess_storage(KM)*& p) { p += N; }
void pointer_mN___ulonglong_KM(unsigned long long chess_storage(KM)*& p) { p -= N; }
void pointer_pI___ulonglong_KM(unsigned long long chess_storage(KM)*& p, int i) { p += i; }
void pointer_mI___ulonglong_KM(unsigned long long chess_storage(KM)*& p, int i) { p -= i; }

unsigned long long chess_storage(KM) global___ulonglong_KM;
unsigned long long chess_storage(KM) garray___ulonglong_KM[N+1];

unsigned long long load_global___ulonglong_KM() { return global___ulonglong_KM; }
unsigned long long load_garray_pN___ulonglong_KM() { return garray___ulonglong_KM[N]; }
unsigned long long load_garray_pI___ulonglong_KM(int i) { return garray___ulonglong_KM[i]; }

//!void store_global___ulonglong_KM(unsigned long long a) { global___ulonglong_KM = a; }
//!void store_garray_pN___ulonglong_KM(unsigned long long a) { garray___ulonglong_KM[N] = a; }
//!void store_garray_pI___ulonglong_KM(unsigned long long a, int i) { garray___ulonglong_KM[i] = a; }


unsigned long long load_indirect0___ulonglong_KM(unsigned long long chess_storage(KM)* p) { return *p; }
unsigned long long load_indexedp1___ulonglong_KM(unsigned long long chess_storage(KM)* p) { return p[ 1]; }
unsigned long long load_indexedm1___ulonglong_KM(unsigned long long chess_storage(KM)* p) { return p[-1]; }
unsigned long long load_indexedpN___ulonglong_KM(unsigned long long chess_storage(KM)* p) { return p[ N]; }
unsigned long long load_indexedmN___ulonglong_KM(unsigned long long chess_storage(KM)* p) { return p[-N]; }
unsigned long long load_indexedpI___ulonglong_KM(unsigned long long chess_storage(KM)* p, int i) { return p[ i]; }
unsigned long long load_indexedmI___ulonglong_KM(unsigned long long chess_storage(KM)* p, int i) { return p[-i]; }

unsigned long long load_postmodp1___ulonglong_KM(unsigned long long chess_storage(KM)*& p) { return *p++; }
unsigned long long load_postmodm1___ulonglong_KM(unsigned long long chess_storage(KM)*& p) { return *p--; }
unsigned long long load_postmodpN___ulonglong_KM(unsigned long long chess_storage(KM)*& p) { unsigned long long t = *p; p += N; return t; }
unsigned long long load_postmodmN___ulonglong_KM(unsigned long long chess_storage(KM)*& p) { unsigned long long t = *p; p -= N; return t; }
unsigned long long load_postmodpI___ulonglong_KM(unsigned long long chess_storage(KM)*& p, int i) { unsigned long long t = *p; p += i; return t; }
unsigned long long load_postmodmI___ulonglong_KM(unsigned long long chess_storage(KM)*& p, int i) { unsigned long long t = *p; p -= i; return t; }

unsigned long long load_premod_p1___ulonglong_KM(unsigned long long chess_storage(KM)*& p) { return *++p; }
unsigned long long load_premod_m1___ulonglong_KM(unsigned long long chess_storage(KM)*& p) { return *--p; }
unsigned long long load_premod_pN___ulonglong_KM(unsigned long long chess_storage(KM)*& p) { p += N; return *p; }
unsigned long long load_premod_mN___ulonglong_KM(unsigned long long chess_storage(KM)*& p) { p -= N; return *p; }
unsigned long long load_premod_pI___ulonglong_KM(unsigned long long chess_storage(KM)*& p, int i) { p += i; return *p; }
unsigned long long load_premod_mI___ulonglong_KM(unsigned long long chess_storage(KM)*& p, int i) { p -= i; return *p; }

//!void store_indirect0___ulonglong_KM(unsigned long long a, unsigned long long chess_storage(KM)* p) { *p = a; }
//!void store_indexedp1___ulonglong_KM(unsigned long long a, unsigned long long chess_storage(KM)* p) { p[ 1] = a; }
//!void store_indexedm1___ulonglong_KM(unsigned long long a, unsigned long long chess_storage(KM)* p) { p[-1] = a; }
//!void store_indexedpN___ulonglong_KM(unsigned long long a, unsigned long long chess_storage(KM)* p) { p[ N] = a; }
//!void store_indexedmN___ulonglong_KM(unsigned long long a, unsigned long long chess_storage(KM)* p) { p[-N] = a; }
//!void store_indexedpI___ulonglong_KM(unsigned long long a, unsigned long long chess_storage(KM)* p, int i) { p[ i] = a; }
//!void store_indexedmI___ulonglong_KM(unsigned long long a, unsigned long long chess_storage(KM)* p, int i) { p[-i] = a; }

//!void store_postmodp1___ulonglong_KM(unsigned long long a, unsigned long long chess_storage(KM)*& p) { *p++ = a; }
//!void store_postmodm1___ulonglong_KM(unsigned long long a, unsigned long long chess_storage(KM)*& p) { *p-- = a; }
//!void store_postmodpN___ulonglong_KM(unsigned long long a, unsigned long long chess_storage(KM)*& p) { *p = a; p += N; }
//!void store_postmodmN___ulonglong_KM(unsigned long long a, unsigned long long chess_storage(KM)*& p) { *p = a; p -= N; }
//!void store_postmodpI___ulonglong_KM(unsigned long long a, unsigned long long chess_storage(KM)*& p, int i) { *p = a; p += i; }
//!void store_postmodmI___ulonglong_KM(unsigned long long a, unsigned long long chess_storage(KM)*& p, int i) { *p = a; p -= i; }

//!void store_premod_p1___ulonglong_KM(unsigned long long a, unsigned long long chess_storage(KM)*& p) { *++p = a; }
//!void store_premod_m1___ulonglong_KM(unsigned long long a, unsigned long long chess_storage(KM)*& p) { *--p = a; }
//!void store_premod_pN___ulonglong_KM(unsigned long long a, unsigned long long chess_storage(KM)*& p) { p += N; *p = a; }
//!void store_premod_mN___ulonglong_KM(unsigned long long a, unsigned long long chess_storage(KM)*& p) { p -= N; *p = a; }
//!void store_premod_pI___ulonglong_KM(unsigned long long a, unsigned long long chess_storage(KM)*& p, int i) { p += i; *p = a; }
//!void store_premod_mI___ulonglong_KM(unsigned long long a, unsigned long long chess_storage(KM)*& p, int i) { p -= i; *p = a; }

//-- float                      // size=1 alignment=1

void pointer_p1___ffloat_KM(float chess_storage(KM)*& p) { ++p; }
void pointer_m1___ffloat_KM(float chess_storage(KM)*& p) { --p; }
void pointer_pN___ffloat_KM(float chess_storage(KM)*& p) { p += N; }
void pointer_mN___ffloat_KM(float chess_storage(KM)*& p) { p -= N; }
void pointer_pI___ffloat_KM(float chess_storage(KM)*& p, int i) { p += i; }
void pointer_mI___ffloat_KM(float chess_storage(KM)*& p, int i) { p -= i; }

float chess_storage(KM) global___ffloat_KM;
float chess_storage(KM) garray___ffloat_KM[N+1];

float load_global___ffloat_KM() { return global___ffloat_KM; }
float load_garray_pN___ffloat_KM() { return garray___ffloat_KM[N]; }
float load_garray_pI___ffloat_KM(int i) { return garray___ffloat_KM[i]; }

//!void store_global___ffloat_KM(float a) { global___ffloat_KM = a; }
//!void store_garray_pN___ffloat_KM(float a) { garray___ffloat_KM[N] = a; }
//!void store_garray_pI___ffloat_KM(float a, int i) { garray___ffloat_KM[i] = a; }


float load_indirect0___ffloat_KM(float chess_storage(KM)* p) { return *p; }
float load_indexedp1___ffloat_KM(float chess_storage(KM)* p) { return p[ 1]; }
float load_indexedm1___ffloat_KM(float chess_storage(KM)* p) { return p[-1]; }
float load_indexedpN___ffloat_KM(float chess_storage(KM)* p) { return p[ N]; }
float load_indexedmN___ffloat_KM(float chess_storage(KM)* p) { return p[-N]; }
float load_indexedpI___ffloat_KM(float chess_storage(KM)* p, int i) { return p[ i]; }
float load_indexedmI___ffloat_KM(float chess_storage(KM)* p, int i) { return p[-i]; }

float load_postmodp1___ffloat_KM(float chess_storage(KM)*& p) { return *p++; }
float load_postmodm1___ffloat_KM(float chess_storage(KM)*& p) { return *p--; }
float load_postmodpN___ffloat_KM(float chess_storage(KM)*& p) { float t = *p; p += N; return t; }
float load_postmodmN___ffloat_KM(float chess_storage(KM)*& p) { float t = *p; p -= N; return t; }
float load_postmodpI___ffloat_KM(float chess_storage(KM)*& p, int i) { float t = *p; p += i; return t; }
float load_postmodmI___ffloat_KM(float chess_storage(KM)*& p, int i) { float t = *p; p -= i; return t; }

float load_premod_p1___ffloat_KM(float chess_storage(KM)*& p) { return *++p; }
float load_premod_m1___ffloat_KM(float chess_storage(KM)*& p) { return *--p; }
float load_premod_pN___ffloat_KM(float chess_storage(KM)*& p) { p += N; return *p; }
float load_premod_mN___ffloat_KM(float chess_storage(KM)*& p) { p -= N; return *p; }
float load_premod_pI___ffloat_KM(float chess_storage(KM)*& p, int i) { p += i; return *p; }
float load_premod_mI___ffloat_KM(float chess_storage(KM)*& p, int i) { p -= i; return *p; }

//!void store_indirect0___ffloat_KM(float a, float chess_storage(KM)* p) { *p = a; }
//!void store_indexedp1___ffloat_KM(float a, float chess_storage(KM)* p) { p[ 1] = a; }
//!void store_indexedm1___ffloat_KM(float a, float chess_storage(KM)* p) { p[-1] = a; }
//!void store_indexedpN___ffloat_KM(float a, float chess_storage(KM)* p) { p[ N] = a; }
//!void store_indexedmN___ffloat_KM(float a, float chess_storage(KM)* p) { p[-N] = a; }
//!void store_indexedpI___ffloat_KM(float a, float chess_storage(KM)* p, int i) { p[ i] = a; }
//!void store_indexedmI___ffloat_KM(float a, float chess_storage(KM)* p, int i) { p[-i] = a; }

//!void store_postmodp1___ffloat_KM(float a, float chess_storage(KM)*& p) { *p++ = a; }
//!void store_postmodm1___ffloat_KM(float a, float chess_storage(KM)*& p) { *p-- = a; }
//!void store_postmodpN___ffloat_KM(float a, float chess_storage(KM)*& p) { *p = a; p += N; }
//!void store_postmodmN___ffloat_KM(float a, float chess_storage(KM)*& p) { *p = a; p -= N; }
//!void store_postmodpI___ffloat_KM(float a, float chess_storage(KM)*& p, int i) { *p = a; p += i; }
//!void store_postmodmI___ffloat_KM(float a, float chess_storage(KM)*& p, int i) { *p = a; p -= i; }

//!void store_premod_p1___ffloat_KM(float a, float chess_storage(KM)*& p) { *++p = a; }
//!void store_premod_m1___ffloat_KM(float a, float chess_storage(KM)*& p) { *--p = a; }
//!void store_premod_pN___ffloat_KM(float a, float chess_storage(KM)*& p) { p += N; *p = a; }
//!void store_premod_mN___ffloat_KM(float a, float chess_storage(KM)*& p) { p -= N; *p = a; }
//!void store_premod_pI___ffloat_KM(float a, float chess_storage(KM)*& p, int i) { p += i; *p = a; }
//!void store_premod_mI___ffloat_KM(float a, float chess_storage(KM)*& p, int i) { p -= i; *p = a; }

//-- double                     // size=2 alignment=1

void pointer_p1___fdouble_KM(double chess_storage(KM)*& p) { ++p; }
void pointer_m1___fdouble_KM(double chess_storage(KM)*& p) { --p; }
void pointer_pN___fdouble_KM(double chess_storage(KM)*& p) { p += N; }
void pointer_mN___fdouble_KM(double chess_storage(KM)*& p) { p -= N; }
void pointer_pI___fdouble_KM(double chess_storage(KM)*& p, int i) { p += i; }
void pointer_mI___fdouble_KM(double chess_storage(KM)*& p, int i) { p -= i; }

double chess_storage(KM) global___fdouble_KM;
double chess_storage(KM) garray___fdouble_KM[N+1];

double load_global___fdouble_KM() { return global___fdouble_KM; }
double load_garray_pN___fdouble_KM() { return garray___fdouble_KM[N]; }
double load_garray_pI___fdouble_KM(int i) { return garray___fdouble_KM[i]; }

//!void store_global___fdouble_KM(double a) { global___fdouble_KM = a; }
//!void store_garray_pN___fdouble_KM(double a) { garray___fdouble_KM[N] = a; }
//!void store_garray_pI___fdouble_KM(double a, int i) { garray___fdouble_KM[i] = a; }


double load_indirect0___fdouble_KM(double chess_storage(KM)* p) { return *p; }
double load_indexedp1___fdouble_KM(double chess_storage(KM)* p) { return p[ 1]; }
double load_indexedm1___fdouble_KM(double chess_storage(KM)* p) { return p[-1]; }
double load_indexedpN___fdouble_KM(double chess_storage(KM)* p) { return p[ N]; }
double load_indexedmN___fdouble_KM(double chess_storage(KM)* p) { return p[-N]; }
double load_indexedpI___fdouble_KM(double chess_storage(KM)* p, int i) { return p[ i]; }
double load_indexedmI___fdouble_KM(double chess_storage(KM)* p, int i) { return p[-i]; }

double load_postmodp1___fdouble_KM(double chess_storage(KM)*& p) { return *p++; }
double load_postmodm1___fdouble_KM(double chess_storage(KM)*& p) { return *p--; }
double load_postmodpN___fdouble_KM(double chess_storage(KM)*& p) { double t = *p; p += N; return t; }
double load_postmodmN___fdouble_KM(double chess_storage(KM)*& p) { double t = *p; p -= N; return t; }
double load_postmodpI___fdouble_KM(double chess_storage(KM)*& p, int i) { double t = *p; p += i; return t; }
double load_postmodmI___fdouble_KM(double chess_storage(KM)*& p, int i) { double t = *p; p -= i; return t; }

double load_premod_p1___fdouble_KM(double chess_storage(KM)*& p) { return *++p; }
double load_premod_m1___fdouble_KM(double chess_storage(KM)*& p) { return *--p; }
double load_premod_pN___fdouble_KM(double chess_storage(KM)*& p) { p += N; return *p; }
double load_premod_mN___fdouble_KM(double chess_storage(KM)*& p) { p -= N; return *p; }
double load_premod_pI___fdouble_KM(double chess_storage(KM)*& p, int i) { p += i; return *p; }
double load_premod_mI___fdouble_KM(double chess_storage(KM)*& p, int i) { p -= i; return *p; }

//!void store_indirect0___fdouble_KM(double a, double chess_storage(KM)* p) { *p = a; }
//!void store_indexedp1___fdouble_KM(double a, double chess_storage(KM)* p) { p[ 1] = a; }
//!void store_indexedm1___fdouble_KM(double a, double chess_storage(KM)* p) { p[-1] = a; }
//!void store_indexedpN___fdouble_KM(double a, double chess_storage(KM)* p) { p[ N] = a; }
//!void store_indexedmN___fdouble_KM(double a, double chess_storage(KM)* p) { p[-N] = a; }
//!void store_indexedpI___fdouble_KM(double a, double chess_storage(KM)* p, int i) { p[ i] = a; }
//!void store_indexedmI___fdouble_KM(double a, double chess_storage(KM)* p, int i) { p[-i] = a; }

//!void store_postmodp1___fdouble_KM(double a, double chess_storage(KM)*& p) { *p++ = a; }
//!void store_postmodm1___fdouble_KM(double a, double chess_storage(KM)*& p) { *p-- = a; }
//!void store_postmodpN___fdouble_KM(double a, double chess_storage(KM)*& p) { *p = a; p += N; }
//!void store_postmodmN___fdouble_KM(double a, double chess_storage(KM)*& p) { *p = a; p -= N; }
//!void store_postmodpI___fdouble_KM(double a, double chess_storage(KM)*& p, int i) { *p = a; p += i; }
//!void store_postmodmI___fdouble_KM(double a, double chess_storage(KM)*& p, int i) { *p = a; p -= i; }

//!void store_premod_p1___fdouble_KM(double a, double chess_storage(KM)*& p) { *++p = a; }
//!void store_premod_m1___fdouble_KM(double a, double chess_storage(KM)*& p) { *--p = a; }
//!void store_premod_pN___fdouble_KM(double a, double chess_storage(KM)*& p) { p += N; *p = a; }
//!void store_premod_mN___fdouble_KM(double a, double chess_storage(KM)*& p) { p -= N; *p = a; }
//!void store_premod_pI___fdouble_KM(double a, double chess_storage(KM)*& p, int i) { p += i; *p = a; }
//!void store_premod_mI___fdouble_KM(double a, double chess_storage(KM)*& p, int i) { p -= i; *p = a; }

//-- void *                     // size=1 alignment=1

void pointer_p1___Pvoid_KM(void * chess_storage(KM)*& p) { ++p; }
void pointer_m1___Pvoid_KM(void * chess_storage(KM)*& p) { --p; }
void pointer_pN___Pvoid_KM(void * chess_storage(KM)*& p) { p += N; }
void pointer_mN___Pvoid_KM(void * chess_storage(KM)*& p) { p -= N; }
void pointer_pI___Pvoid_KM(void * chess_storage(KM)*& p, int i) { p += i; }
void pointer_mI___Pvoid_KM(void * chess_storage(KM)*& p, int i) { p -= i; }

void * chess_storage(KM) global___Pvoid_KM;
void * chess_storage(KM) garray___Pvoid_KM[N+1];

void * load_global___Pvoid_KM() { return global___Pvoid_KM; }
void * load_garray_pN___Pvoid_KM() { return garray___Pvoid_KM[N]; }
void * load_garray_pI___Pvoid_KM(int i) { return garray___Pvoid_KM[i]; }

//!void store_global___Pvoid_KM(void * a) { global___Pvoid_KM = a; }
//!void store_garray_pN___Pvoid_KM(void * a) { garray___Pvoid_KM[N] = a; }
//!void store_garray_pI___Pvoid_KM(void * a, int i) { garray___Pvoid_KM[i] = a; }


void * load_indirect0___Pvoid_KM(void * chess_storage(KM)* p) { return *p; }
void * load_indexedp1___Pvoid_KM(void * chess_storage(KM)* p) { return p[ 1]; }
void * load_indexedm1___Pvoid_KM(void * chess_storage(KM)* p) { return p[-1]; }
void * load_indexedpN___Pvoid_KM(void * chess_storage(KM)* p) { return p[ N]; }
void * load_indexedmN___Pvoid_KM(void * chess_storage(KM)* p) { return p[-N]; }
void * load_indexedpI___Pvoid_KM(void * chess_storage(KM)* p, int i) { return p[ i]; }
void * load_indexedmI___Pvoid_KM(void * chess_storage(KM)* p, int i) { return p[-i]; }

void * load_postmodp1___Pvoid_KM(void * chess_storage(KM)*& p) { return *p++; }
void * load_postmodm1___Pvoid_KM(void * chess_storage(KM)*& p) { return *p--; }
void * load_postmodpN___Pvoid_KM(void * chess_storage(KM)*& p) { void * t = *p; p += N; return t; }
void * load_postmodmN___Pvoid_KM(void * chess_storage(KM)*& p) { void * t = *p; p -= N; return t; }
void * load_postmodpI___Pvoid_KM(void * chess_storage(KM)*& p, int i) { void * t = *p; p += i; return t; }
void * load_postmodmI___Pvoid_KM(void * chess_storage(KM)*& p, int i) { void * t = *p; p -= i; return t; }

void * load_premod_p1___Pvoid_KM(void * chess_storage(KM)*& p) { return *++p; }
void * load_premod_m1___Pvoid_KM(void * chess_storage(KM)*& p) { return *--p; }
void * load_premod_pN___Pvoid_KM(void * chess_storage(KM)*& p) { p += N; return *p; }
void * load_premod_mN___Pvoid_KM(void * chess_storage(KM)*& p) { p -= N; return *p; }
void * load_premod_pI___Pvoid_KM(void * chess_storage(KM)*& p, int i) { p += i; return *p; }
void * load_premod_mI___Pvoid_KM(void * chess_storage(KM)*& p, int i) { p -= i; return *p; }

//!void store_indirect0___Pvoid_KM(void * a, void * chess_storage(KM)* p) { *p = a; }
//!void store_indexedp1___Pvoid_KM(void * a, void * chess_storage(KM)* p) { p[ 1] = a; }
//!void store_indexedm1___Pvoid_KM(void * a, void * chess_storage(KM)* p) { p[-1] = a; }
//!void store_indexedpN___Pvoid_KM(void * a, void * chess_storage(KM)* p) { p[ N] = a; }
//!void store_indexedmN___Pvoid_KM(void * a, void * chess_storage(KM)* p) { p[-N] = a; }
//!void store_indexedpI___Pvoid_KM(void * a, void * chess_storage(KM)* p, int i) { p[ i] = a; }
//!void store_indexedmI___Pvoid_KM(void * a, void * chess_storage(KM)* p, int i) { p[-i] = a; }

//!void store_postmodp1___Pvoid_KM(void * a, void * chess_storage(KM)*& p) { *p++ = a; }
//!void store_postmodm1___Pvoid_KM(void * a, void * chess_storage(KM)*& p) { *p-- = a; }
//!void store_postmodpN___Pvoid_KM(void * a, void * chess_storage(KM)*& p) { *p = a; p += N; }
//!void store_postmodmN___Pvoid_KM(void * a, void * chess_storage(KM)*& p) { *p = a; p -= N; }
//!void store_postmodpI___Pvoid_KM(void * a, void * chess_storage(KM)*& p, int i) { *p = a; p += i; }
//!void store_postmodmI___Pvoid_KM(void * a, void * chess_storage(KM)*& p, int i) { *p = a; p -= i; }

//!void store_premod_p1___Pvoid_KM(void * a, void * chess_storage(KM)*& p) { *++p = a; }
//!void store_premod_m1___Pvoid_KM(void * a, void * chess_storage(KM)*& p) { *--p = a; }
//!void store_premod_pN___Pvoid_KM(void * a, void * chess_storage(KM)*& p) { p += N; *p = a; }
//!void store_premod_mN___Pvoid_KM(void * a, void * chess_storage(KM)*& p) { p -= N; *p = a; }
//!void store_premod_pI___Pvoid_KM(void * a, void * chess_storage(KM)*& p, int i) { p += i; *p = a; }
//!void store_premod_mI___Pvoid_KM(void * a, void * chess_storage(KM)*& p, int i) { p -= i; *p = a; }


} //extern "C"  (550 functions of which 242 skipped)
