
// File generated by noodle version N-2018.03#7d02e3ca79#180723, Fri Jan 25 16:14:37 2019
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// noodle -Pc -Iisg +wisg -D__tct_patch__=300 -D__chess__ -D__programmers_view__ tinycore2

// File: builtin_conversions.c
// Test C built-in conversions  (except any left undefined)

extern "C" {


//-- int

//!int                 bicnv___sint___uint           (unsigned            a) { return a; }

//-- unsigned

//!unsigned            bicnv___uint___sint           (int                 a) { return a; }

} //extern "C"  (2 functions of which 2 skipped)
