
// File generated by noodle version N-2018.03#7d02e3ca79#180723, Tue Jan 15 15:18:08 2019
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// noodle -Pc -Iisg +wisg -D__tct_patch__=300 -D__chess__ -D__programmers_view__ tinycore2

// File: compile_time_constants.c
// Test compile-time constants : size and alignment in default and other suitable memories

extern "C" {

const int szal___sint_DM                          [] =  //  1,  1
    { sizeof(int /*chess_storage(DM)*/               ), chess_alignof(int /*chess_storage(DM)*/               ) };
const int szal___uint_DM                          [] =  //  1,  1
    { sizeof(unsigned /*chess_storage(DM)*/          ), chess_alignof(unsigned /*chess_storage(DM)*/          ) };
const int szal___Pvoid_DM                         [] =  //  1,  1
    { sizeof(void * /*chess_storage(DM)*/            ), chess_alignof(void * /*chess_storage(DM)*/            ) };

} //extern "C"  (3 functions)
