
// File generated by noodle version N-2018.03#7d02e3ca79#180723, Tue Jan 15 15:18:08 2019
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// noodle -Pc -Iisg +wisg -D__tct_patch__=300 -D__chess__ -D__programmers_view__ tinycore2

// File: memory_PM.c
// Test memory PM pointer arithmetic stand-alone and with load/store

//!! no load/store instructions found

#ifndef N // arbitrary value, adapt at will
#define N 7
#endif

extern "C" {

//!! int

//!! unsigned

//!! void *


} //extern "C"  (0 functions)
