
// File generated by noodle version N-2018.03#7d02e3ca79#180723, Fri Jan 25 16:14:37 2019
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// noodle -Pc -Iisg +wisg -D__tct_patch__=300 -D__chess__ -D__programmers_view__ tinycore2

// File: register_moves.c
// Test register moves
// (Output is written as an in-out reference, so that it cannot be overlayed with the input)

//! Connection analysis may reveal that certain moves are not available, and those tests are skipped.
//! Note that the connection may be direct or indirect.
//! However, indirect connections via spill memory are not considered at this time!

extern "C" {

//-- int

void move___sint_R_R(int& chess_storage(R) r, int chess_storage(R) a) { r = a; }

//-- unsigned

void move___uint_R_R(unsigned& chess_storage(R) r, unsigned chess_storage(R) a) { r = a; }

//-- void *

void move___Pvoid_R_R(void *& chess_storage(R) r, void * chess_storage(R) a) { r = a; }


} //extern "C"  (3 functions)
