
// File generated by noodle version N-2018.03#7d02e3ca79#180723, Tue Jan 15 15:18:08 2019
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// noodle -Pc -Iisg +wisg -D__tct_patch__=300 -D__chess__ -D__programmers_view__ tinycore2

// File: simple_function.c
// Test empty function (return only) and simple function call (without arguments)
// (requires spilling of the link register)

extern "C" {

void empty_function() { }

void simple_function_call()
{
    empty_function();  // nested call
    empty_function();  // tail call (may be replaced by jump)
}

void indirect_function_call(void (*fnptr)())
{
    fnptr();  // nested call
    fnptr();  // tail call (may be replaced by indirect jump)
}


} //extern "C"  (3 functions)
