
// File generated by noodle version N-2018.03#7d02e3ca79#180723, Fri Jan 25 16:14:37 2019
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// noodle -Pc -Iisg +wisg -D__tct_patch__=300 -D__chess__ -D__programmers_view__ tinycore2

// File: standalone_intrinsics.c
// Test standalone intrinsics  (in global namespace)
// (Outputs that cannot be returned as function parameters are discarded)

extern "C" {


} //extern "C"  (0 functions)
