
// File generated by noodle version N-2018.03#7d02e3ca79#180723, Fri Jan 11 22:24:42 2019
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// noodle -B -I/users/benacer/Desktop/sha256_orig/sha256/lib -I/users/benacer/Desktop/sha256_orig/sha256/lib/isg -I/users/benacer/Desktop/sha256_orig/sha256/lib/runtime/include -I../../io_modules -I/CMC/tools/synopsys/asip_designer_vN-2018.03-SP3/linux64/chessdir/../examples/io_modules -D__tct_patch__=300 -itlx_chess.h +wRelease/chesswork io.c tlx

.dir 0 "/users/benacer/Desktop/sha256_orig/sha256/lib/runtime/include"
.undef global text _main_init
.text local 1 void_exit___sint
.src_ref 0 "stdlib.h" 58
      ori r2,r4,#0   ; move R4 to R2
.src_ref 0 "stdlib.h" 59
      nop            ; flush pipeline in case ISS breakpoint stage is early
.src_ref 0 "stdlib.h" 60
      nop
.src_ref 0 "stdlib.h" 61
      nop
.src_ref 0 "stdlib.h" 62
      nop
.src_ref 0 "stdlib.h" 63
.stop
.src_ref 0 "stdlib.h" 64
      nop
