
; File generated by darts version N-2018.03#7d02e3ca79#180723, Fri Jan 25 16:18:42 2019
; Copyright 2014-2018 Synopsys, Inc. All rights reserved.
; darts -I/users/Cours/inf8505/12/Documents/inf8505/lab1/tinycore2/labs/lab5/lib +p -d -D__tct_patch__=300 +u Release/srl_test tinycore2

; Release: ipd N-2018.03-SP3

.text_segment PM      0	   
.entry_point
.label _main
	/*      0      "10100000000000" */    	r0.hi = 0
	/*      1      "10100000001000" */    	r1.hi = 0
	/*      2      "11000000000000" */    	r0 |= 0
	/*      3      "11000000001001" */    	r1 |= 1
	/*      4      "00100000000000" */    	r0 = DM[r0]
	/*      5      "00100000001001" */    	r1 = DM[r1]
	/*      6      "10000000010001" */    	r2 = 1
	/*      7      "01000101000001" */    	r0 = r0 >> r1
	/*      8      "00100101011000" */    	r3 = r0
	/*      9      "01000101000010" */    	r0 = r0 >> r2
	/*     10      "10100000001000" */    	r1.hi = 0
	/*     11      "00101010000000" */    	rts
	/*     12      "11000000001010" */    	r1 |= 2
	/*     13      "00100010001011" */    	DM[r1] = r3

.data_segment DM      0	   
.label a
	0xff
.label b
	0x2

.bss_segment DM      2	    1
