
; File generated by darts version N-2018.03#7d02e3ca79#180723, Fri Jan 25 16:18:42 2019
; Copyright 2014-2018 Synopsys, Inc. All rights reserved.
; darts -I/users/Cours/inf8505/12/Documents/inf8505/lab1/tinycore2/labs/lab5/lib +p -d -D__tct_patch__=300 Release/srl_test.o tinycore2

; Release: ipd N-2018.03-SP3
.data_segment_name
.data global 1 a DM
	0xff

.data_segment_name
.data global 1 b DM
	0x2

.data_segment_name
.bss global 1 c DM 1

.text_segment_name
.text global 0 _main
.rela 3 a 0
	/*      0 "10100000000000" */    r0.hi = 0
.rela 3 b 0
	/*      1 "10100000001000" */    r1.hi = 0
.rela 4 a 0
	/*      2 "11000000000000" */    r0 |= 0
.rela 4 b 0
	/*      3 "11000000001000" */    r1 |= 0
	/*      4 "00100000000000" */    r0 = DM[r0]
	/*      5 "00100000001001" */    r1 = DM[r1]
	/*      6 "10000000010001" */    r2 = 1
	/*      7 "01000101000001" */    r0 = r0 >> r1
	/*      8 "00100101011000" */    r3 = r0
	/*      9 "01000101000010" */    r0 = r0 >> r2
.rela 3 c 0
	/*     10 "10100000001000" */    r1.hi = 0
	/*     11 "00101010000000" */    rts
.rela 4 c 0
	/*     12 "11000000001000" */    r1 |= 0
.label _main__end
	/*     13 "00100010001011" */    DM[r1] = r3

.undef global data a

.undef global data b

.undef global data c

